(function(g){var window=this;'use strict';var o_=function(r){r.publish("cardstatechange",r.lf()&&r.Ou()?1:0)},qC=function(r,p){var I=g.qK(p);
const S=I?p:arguments;for(I=I?0:1;I<S.length;I++){if(r==null)return;r=r[S[I]]}return r},UeY=function(r){const p=g.U3(r);
r=g.RA(r);return new g.Q3(p.x,p.y,r.width,r.height)},PpY=function(r,p,I){let S;
return S=g.$X(r,p,function(){g.id(S);I.apply(r,arguments)},{})},kJ=function(r){r=g.k9(r);
delete MC[r];g.mV(MC)&&Z2&&Z2.stop()},AgU=function(){Z2||(Z2=new g.pa(function(){nQr()},20));
const r=Z2;r.isActive()||r.start()},nQr=function(){var r=g.TB();
g.ZY(MC,function(p){H2P(p,r)});
g.mV(MC)||AgU()},cE=function(r,p,I,S){g.JZ.call(this);
if(!Array.isArray(r)||!Array.isArray(p))throw Error("Start and end parameters must be arrays");if(r.length!=p.length)throw Error("Start and end points must be the same length");this.U=r;this.K=p;this.duration=I;this.C=S;this.coords=[];this.progress=this.J=0;this.N=null},H2P=function(r,p){p<r.startTime&&(r.endTime=p+r.endTime-r.startTime,r.startTime=p);
r.progress=(p-r.startTime)/(r.endTime-r.startTime);r.progress>1&&(r.progress=1);r.J=1E3/(p-r.N);r.N=p;LQa(r,r.progress);r.progress==1?(r.W=0,kJ(r),r.onFinish(),r.uP()):r.isPlaying()&&r.m1()},LQa=function(r,p){typeof r.C==="function"&&(p=r.C(p));
r.coords=Array(r.U.length);for(let I=0;I<r.U.length;I++)r.coords[I]=(r.K[I]-r.U[I])*p+r.U[I]},ROY=function(r,p){g.Cp.call(this,r);
this.coords=p.coords;this.x=p.coords[0];this.y=p.coords[1];this.z=p.coords[2];this.duration=p.duration;this.progress=p.progress;this.fps=p.J;this.state=p.W},g8=function(r,p,I,S,a){cE.call(this,p,I,S,a);
this.element=r},TF=function(r,p,I,S,a){if(p.length!=2||I.length!=2)throw Error("Start and end points must be 2D");
g8.call(this,r,p,I,S,a)},rPA=function(r){return Math.pow(r,3)},pbn=function(r){return 3*r*r-2*r*r*r},K3=function(r){return r.baseUrl||null},Qr=function(r,p){return g.Fi(g.P5(r,p),I=>!!I)},It5=function(r,p,I){function S(oQ){var mo=oQ.hovercardButton;
if(!mo)return null;mo=mo.subscribeButtonRenderer;if(!mo)return null;const UK=B(mo.unsubscribedButtonText),go=B(mo.subscribedButtonText);let uh,oo;mo.subscribed?(uh=B(mo.subscriberCountWithUnsubscribeText),oo=B(mo.subscriberCountText)):(uh=B(mo.subscriberCountText),oo=B(mo.subscriberCountWithSubscribeText));let up=null;return oQ.signinEndpoint&&((up=qC(oQ,"signinEndpoint","webNavigationEndpointData","url"))||(up=g.m(mo.signInEndpoint?.commandMetadata,g.Zx)?.url),!up)?null:UK&&(go||up)?{subscribed:mo.subscribed,
subscribeText:UK,subscribeCount:uh,unsubscribeText:go,unsubscribeCount:oo,enabled:mo.enabled,signinUrl:up,classic:oQ.useClassicSubscribeButton}:null}
function a(oQ){if(oQ){var mo=[],UK=oQ.videoId;UK&&mo.push("v="+UK);(UK=oQ.playlistId)&&mo.push("list="+UK);(oQ=oQ.startTimeSeconds)&&mo.push("t="+oQ);return"/watch?"+mo.join("&")}}
function B(oQ){if(!oQ)return null;const mo=oQ.simpleText;return mo?mo:oQ.runs?g.P5(oQ.runs,UK=>UK.text).join(""):null}
p=p.endscreenElementRenderer;if(!p)return null;const N=p.style,v=p.endpoint||{};let e=null;var C=null,b=!1;let J=null,W=null,X=null,d=null;var M=!1;let T=null,E=null;var Q=null;let D=null,z=null,SF=null;if(N==="VIDEO")g.m(v,g.E0)?e=g.m(v,g.E0).url:(SF=g.m(v,g.fe),e=a(SF)),C=!1,J=r,p.thumbnailOverlays?(b=p.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,W=B(b.text),b=b.style==="LIVE"):W=B(p.videoDuration);else if(N==="PLAYLIST")g.m(v,g.E0)?e=g.m(v,g.E0).url:(SF=g.m(v,g.fe),e=a(SF)),C=!1,J=
r,X=B(p.playlistLength);else if(N==="CHANNEL"){if(M=qC(v,"browseEndpoint","browseId"))d=M,e=`/channel/${d}`;C=!1;J="new";(M=!!p.isSubscribe)?T=S(p):E=B(p.subscribersText)}else N==="WEBSITE"?((Q=qC(v,"urlEndpoint","url"))&&(e=Q),C=!0,J="new",Q=p.icon.thumbnails[0].url):N==="CREATOR_MERCHANDISE"&&(p.productPrice&&(D=B(p.productPrice)),p.additionalFeesText&&(z=B(p.additionalFeesText)),(C=qC(v,"urlEndpoint","url"))&&(e=C),C=!0,J="new");r=qC(p,"title","accessibility","accessibilityData","label");const aQ=
p.endpoint?p.endpoint.clickTrackingParams:null;let zB="";if(p.metadata){const oQ=B(p.metadata);oQ&&(zB=oQ)}return{id:`element-${I}`,type:N,title:B(p.title),metadata:zB,callToAction:B(p.callToAction),XS:p.image,iconUrl:Q,left:Number(p.left),width:Number(p.width),top:Number(p.top),aspectRatio:Number(p.aspectRatio),startMs:Math.floor(Number(p.startMs)),endMs:Math.floor(Number(p.endMs)),videoDuration:W,fK:b,playlistLength:X,channelId:d,subscribeButton:T,subscribersText:E,isSubscribe:M,targetUrl:e||null,
SH:C,sessionData:aQ?{itct:aQ}:null,dC:J,Hd:r?r:null,isPlaceholder:p.isPlaceholder,impressionUrls:Qr(p.impressionUrls||[],K3),UP:Qr(p.hovercardShowUrls||[],K3),clickUrls:Qr(v.loggingUrls||[],K3),visualElement:g.Vb(p.trackingParams),productPrice:D,additionalFeesText:z,watchEndpoint:SF||null}},Eu=function(r,p){const I={startMs:Math.floor(Number(r.startMs)),
impressionUrls:Qr(r.impressionUrls||[],K3),elements:Qr(r.elements||[],(S,a)=>It5(p,S,a))};
r.trackingParams&&(I.visualElement=g.Vb(r.trackingParams));return I},j2=function(r){return r.player.G().playerStyle==="creator-endscreen-editor"},$mY=function(r){return r.player.getVideoData().Ur?"current":r.Y?"new":"current"},tp=function(r,p,I=!0){r.player.Vx("creatorendscreen");
r.Z&&(r.Z.dispose(),r.Z=null,r.C.dispose(),r.C=null);for(var S of Object.values(r.U))S.dispose();r.U={};r.J={};r.D.length>0&&(r.D.forEach(a=>{a.dispose()}),r.D.length=0);
r.W&&(g.ee(r.W,"ytp-ce-element-show"),r.W.setAttribute("aria-hidden","true"));r.K=0;if((r.endscreen=p)&&p.elements){I&&ixP(r);I=[];S=new g.Y0(p.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});I.push(S);r.player.G().U||(r.Z=new g.H({S:"div",O:"ytp-ce-shadow"}),g.EX(r.player,r.Z.element,4),r.C=new g.Pc(r.Z,200));for(S=0;S<p.elements.length;++S){const a=p.elements[S],B=S3Y(r,a);if(!B){g.Qb(new g.oa("buildEndscreenElement null",a));continue}r.U[a.id]=B;r.J[a.id]=a;g.EX(r.player,
B.element,4);const N=new g.Y0(a.startMs,a.endMs,{id:"ytp-ce-element-"+a.id,namespace:"creatorendscreen"});I.push(N);atg(r,B,a)}r.player.W0(I);r.QH()}},BSY=function(r){var p=r.player.getVideoData(),I=p.videoId;
r.N&&r.N.abort();I={method:"POST",onFinish:a=>{var B=r.N=null;a.status===200&&(a=a.responseText,a.substring(0,3)===")]}"&&(a=a.substring(3),B=JSON.parse(a),B=Eu(B,$mY(r))));tp(r,B)},
urlParams:{v:I},withCredentials:!0};r.Y&&(I.urlParams.ptype="embedded");const S=p.I5;S&&(I.postParams={ad_tracking:S});if(p=g.taQ(p))if(p=g.Dq(p),p=g.Qi(p))r.N=g.AW(p,I)},ixP=function(r){const p=g.GJ(),I=g.oV();
I&&p&&r.endscreen.visualElement&&g.gg(g.PV)(void 0,I,p,r.endscreen.visualElement)},S3Y=function(r,p){var I=null;
switch(p.type){case "VIDEO":r={S:"div",vI:["ytp-ce-element","ytp-ce-video"],j:{tabindex:"0","aria-label":p.Hd||"","aria-hidden":"true"},A:[{S:"div",O:"ytp-ce-element-shadow"},{S:"div",O:"ytp-ce-covering-image",j:D2(p)},{S:"div",O:"ytp-ce-covering-shadow-top"},{S:"a",O:"ytp-ce-covering-overlay",j:{href:hp(r,p.targetUrl),tabindex:"-1"},A:[{S:"div",vI:["ytp-ce-video-title","ytp-webkit-ellipsis"],j:{dir:g.wd(p.title||"")},uC:p.title},{S:"div",O:p.fK?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
uC:p.videoDuration||void 0}]}]};I=new g.H(r);break;case "PLAYLIST":r={S:"div",vI:["ytp-ce-element","ytp-ce-playlist"],j:{tabindex:"0","aria-label":p.Hd||"","aria-hidden":"true"},A:[{S:"div",O:"ytp-ce-element-shadow"},{S:"div",O:"ytp-ce-covering-image",j:D2(p)},{S:"div",O:"ytp-ce-covering-shadow-top"},{S:"a",O:"ytp-ce-covering-overlay",j:{href:hp(r,p.targetUrl),tabindex:"-1"},A:[{S:"div",vI:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],j:{dir:g.wd(p.title||"")},uC:p.title},{S:"div",O:"ytp-ce-playlist-count",
A:[{S:"div",O:"ytp-ce-playlist-icon"},{S:"div",O:"ytp-ce-playlist-count-text",uC:p.playlistLength||void 0}]}]}]};I=new g.H(r);break;case "CHANNEL":I={S:"div",vI:["ytp-ce-element","ytp-ce-channel",p.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],j:{tabindex:"0","aria-label":p.Hd||"","aria-hidden":"true"},A:[{S:"div",O:"ytp-ce-element-shadow"},{S:"div",O:"ytp-ce-expanding-overlay",A:[{S:"div",O:"ytp-ce-expanding-overlay-hider"},{S:"div",O:"ytp-ce-expanding-overlay-background"},{S:"div",O:"ytp-ce-expanding-overlay-content",
A:[{S:"div",O:"ytp-ce-expanding-overlay-body",A:[{S:"div",O:"ytp-ce-expanding-overlay-body-padding",A:[{S:"a",vI:["ytp-ce-channel-title","ytp-ce-link"],j:{href:hp(r,p.targetUrl),target:"_blank",tabindex:"-1",dir:g.wd(p.title||"")},uC:p.title},p.subscribeButton?{S:"div",O:"ytp-ce-subscribe-container",A:[{S:"div",O:"ytp-ce-channel-subscribe"}]}:"",p.subscribersText?{S:"div",O:"ytp-ce-channel-subscribers-text",uC:p.subscribersText}:"",p.metadata?{S:"div",vI:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],uC:p.metadata}:""]}]}]}]},{S:"div",O:"ytp-ce-expanding-image",j:D2(p)}]};I=new g.H(I);const a=g.Ha(document,"div","ytp-ce-channel-subscribe",I.element)[0];if(p.subscribeButton&&p.channelId){g.NL(a,"ytp-ce-subscribe-button");let B;if(r.player.G().U){var S=null;B=p.sessionData.itct}else S="endscreen",B=null;S=new g.dl(p.subscribeButton.subscribeText,p.subscribeButton.subscribeCount,p.subscribeButton.unsubscribeText,p.subscribeButton.unsubscribeCount,!!p.subscribeButton.enabled,!!p.subscribeButton.classic,
p.channelId,!!p.subscribeButton.subscribed,S,B,r.player,!1);a.appendChild(S.element);r.D.push(S)}break;case "WEBSITE":r={S:"div",vI:["ytp-ce-element","ytp-ce-website"],j:{tabindex:"0","aria-label":p.Hd||"","aria-hidden":"true"},A:[{S:"div",O:"ytp-ce-element-shadow"},{S:"div",O:"ytp-ce-expanding-overlay",A:[{S:"div",O:"ytp-ce-expanding-overlay-hider"},{S:"div",O:"ytp-ce-expanding-overlay-background"},{S:"div",O:"ytp-ce-expanding-overlay-content",A:[{S:"div",O:"ytp-ce-expanding-overlay-body",A:[{S:"div",
O:"ytp-ce-expanding-overlay-body-padding",A:[{S:"div",O:"ytp-ce-website-title",j:{dir:g.wd(p.title||"")},uC:p.title},{S:"div",O:"ytp-ce-website-metadata",uC:p.metadata},{S:"a",vI:["ytp-ce-website-goto","ytp-ce-link"],j:{href:hp(r,p.targetUrl),target:"_blank",tabindex:"-1"},uC:p.callToAction}]}]}]}]},{S:"div",O:"ytp-ce-expanding-image",j:D2(p)},{S:"div",O:"ytp-ce-expanding-icon",j:NSn(p.iconUrl)}]};I=new g.H(r);break;case "CREATOR_MERCHANDISE":I="",p.productPrice&&(I={S:"div",O:"ytp-ce-merchandise-price-container",
A:[{S:"div",O:"ytp-ce-merchandise-price",uC:p.productPrice}]},p.additionalFeesText&&I.A.push({S:"div",O:"ytp-ce-merchandise-additional-fees",uC:p.additionalFeesText})),r={S:"div",vI:["ytp-ce-element","ytp-ce-merchandise"],j:{tabindex:"0","aria-label":p.Hd||"","aria-hidden":"true"},A:[{S:"div",O:"ytp-ce-element-shadow"},{S:"div",O:"ytp-ce-expanding-overlay",A:[{S:"div",O:"ytp-ce-expanding-overlay-hider"},{S:"div",O:"ytp-ce-expanding-overlay-background"},{S:"div",O:"ytp-ce-expanding-overlay-content",
A:[{S:"div",O:"ytp-ce-expanding-overlay-body",A:[{S:"div",O:"ytp-ce-expanding-overlay-body-padding",A:[{S:"div",O:"ytp-ce-merchandise-title",j:{dir:g.wd(p.title||"")},uC:p.title},I,{S:"div",O:"ytp-ce-merchandise-metadata",uC:p.metadata},{S:"a",vI:["ytp-ce-merchandise-goto","ytp-ce-link"],j:{href:hp(r,p.targetUrl),target:"_blank",tabindex:"-1"},uC:p.callToAction}]}]}]}]},{S:"div",O:"ytp-ce-expanding-image",j:D2(p)},{S:"div",O:"ytp-ce-merchandise-invideo-cta-container",A:[{S:"div",O:"ytp-ce-merchandise-invideo-cta",
uC:p.callToAction||void 0}]}]},I=new g.H(r)}p.isPlaceholder&&g.NL(I.element,"ytp-ce-placeholder");return I},atg=function(r,p,I){function S(){N(1)}
function a(){N(-1)}
p.listen("mouseenter",()=>{xJ(r,p,I)});
p.listen("mouseleave",()=>{zF(r,p,I)});
r.player.G().U||p.listen("click",()=>{g.NL(p.element,"ytp-ce-element-hover")});
p.listen("click",v=>{vYY(r,I,v)});
p.listen("keypress",v=>{vYY(r,I,v)});
p.listen("focus",()=>{xJ(r,p,I)});
p.listen("blur",()=>{zF(r,p,I)});
p.listen("touchstart",()=>{xJ(r,p,I)});
var B=g.L2("ytp-ce-expanding-overlay-hider",p.element);B&&p.B(B,"touchstart",v=>{v.stopPropagation();g.ee(p.element,"ytp-ce-element-hover");g.ee(p.element,"ytp-ce-force-expand")});
p.listen("keydown",v=>{r.iC=v.keyCode===9&&!v.shiftKey});
const N=v=>{r.K+=v;r.K>0?(g.NL(p.element,"ytp-ce-force-expand"),mK(r,I.id,!0)):(g.ee(p.element,"ytp-ce-force-expand"),g.ee(p.element,"ytp-ce-element-hover"),mK(r,I.id,!1))};
B=v=>{v&&(p.listen("blur",()=>{v.style.display!="none"&&r.iC&&v.focus()}),p.B(v,"focus",S),p.B(v,"blur",a))};
B(g.L2("ytp-sb-subscribe",p.element));B(g.L2("ytp-sb-unsubscribe",p.element));p.listen("focus",S);p.listen("blur",a)},u3=function(r,p,I){function S(){B||(a++,a===p.length&&(N.stop(),I&&I()))}
if(!p||p.length===0||j2(r))I&&I();else{p=e1U(r,p);var a=0,B=!1,N=new g.pa(()=>{B=!0;I&&I()},1E3,r);
N.start();for(r=0;r<p.length;r++)g.Ym(p[r],S)}},D2=function(r){let p;
r.XS&&(p=r.XS.thumbnails);return NSn(p?p[p.length-1].url:null)},hp=function(r,p){r=r.player.G();
if(p){if(p.startsWith("//"))return r.protocol+":"+p;if(p.startsWith("/"))return g.td(r)+p}else return"";return p},NSn=function(r){return r?{style:"background-image: url("+r+")"}:{}},xJ=function(r,p,I){g.BX(p.element,"ytp-ce-element-hover")||(I.type==="VIDEO"||I.type==="PLAYLIST"?g.NL(p.element,"ytp-ce-element-hover"):r.player.G().U?(new g.pa(()=>{g.NL(p.element,"ytp-ce-element-hover")},200)).start():g.NL(p.element,"ytp-ce-element-hover"),u3(r,I.UP),mK(r,I.id,!0))},zF=function(r,p,I){g.ee(p.element,
"ytp-ce-element-hover");
g.ee(p.element,"ytp-ce-force-expand");mK(r,I.id,!1)},vYY=function(r,p,I){if(p.targetUrl&&(!I||I.type!=="keypress"||I.keyCode===13)){for(var S=I.target;S&&!g.BX(S,"ytp-ce-element");){g.BX(S,"subscribe-label")&&l3(r,p);
if(g.BX(S,"ytp-ce-channel-subscribe"))return;S=S.parentElement||null}if(!S||g.BX(S,"ytp-ce-element-hover")){I.preventDefault();I.stopPropagation();if(S=r.U[p.id])zF(r,S,p),S.element.blur();if(I.ctrlKey||I.metaKey||p.dC==="new")l3(r,p),r.player.sendVideoStatsEngageEvent(17,void 0),r.player.pauseVideo(),I=g.Dq(hp(r,p.targetUrl)),I=g.Qi(I),g.IO(I,void 0,p.sessionData);else{const a=g.kc(r.player.G())||r.player.getVideoData().Ur,B=()=>{var N=hp(r,p.targetUrl),v=p.sessionData,e=p.watchEndpoint;const C=
g.Gh(N);a&&C&&(C.v||C.list)?r.player.zd(C.v,v,C.list,!1,void 0,e||void 0):g.pm(N,v)};
l3(r,p,()=>{r.player.sendVideoStatsEngageEvent(17,B)})}}}},mK=function(r,p,I){r.Z&&(I?r.C.show():r.C.hide());
for(const S of Object.keys(r.U))S!==p&&g.K(r.U[S].element,"ytp-ce-element-shadow-show",I)},l3=function(r,p,I){u3(r,p.clickUrls,I);
(r=g.oV())&&p.SH&&g.Sy(r,p.visualElement)},e1U=function(r,p){var I=r.player.getVideoData().clientPlaybackNonce;
r=r.player.getCurrentTime().toFixed(2);I={CPN:I,AD_CPN:I,MT:r};r=[];for(let S=0;S<p.length;S++)r.push(Ci1(p[S],I));return r},Ci1=function(r,p){return r.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,I=>{let S=unescape(I);
S=S.substring(1,S.length-1);return p[S]?escape(p[S]):I})},bxV=function(r){return typeof r==="string"?r:""},YJ=function(r,p,I){for(const S in p)if(p[S]===r)return r;
return I},Fs=function(r){if(!r)return null;
var p=g.Dq(bxV(r.value));p=g.Qi(p);if(!p)return null;const I=YJ(r.target,JPn,"current");if(I==null)r=null;else{var S=r.show_link_icon;r=new sAY(p,I,S==="true"||S==="false"?S==="true":!0,r.pause_on_navigation!=null?r.pause_on_navigation:!0)}return r},yPY=function(r){if(!r)return null;
const p=YJ(r.type,WtP),I=YJ(r.trigger,XbA);r=r.url;r=Array.isArray(r)&&r.length?r[0]:r;r=Fs(r?r:null);return p?new Ox1(p,I,r):null},dmA=function(r,p){return g.rP(r.action,p)},Uu=function(r,p){r="background-image: url("+r+");";
const I=[];p&&I.push(p);return{S:"div",O:"iv-card-image",j:{style:r},A:I}},n3=function(r){return r.customMessage?PE("div","iv-card-message",r.customMessage):""},Ap=function(r){if(!r.metaInfo||r.metaInfo.length===0)return"";
const p=[];for(const I of r.metaInfo)p.push(PE("li","",I));return{S:"ul",O:"iv-card-meta-info",A:p}},HE=function(r,p,I,S){if(S)for(const a of p)r.W(a,S,I.id,I.sessionData,I.uf.click,5)},PE=function(r,p,I){p?typeof p==="string"?p={"class":p}:Array.isArray(p)&&(p={"class":p.join(" ")}):p={};
p.dir=g.wd(I);return{S:r,j:p,uC:I}},VBY=function(r){if(!r.customMessage)return"";
const p=["iv-card-action","iv-card-primary-link"],I={};r.Bd&&(p.push("iv-card-action-icon"),I.style="background-image: url("+r.Bd+");");I.dir=g.wd(r.customMessage);const S=[{S:"span",uC:r.customMessage}];r.showLinkIcon&&(S.push("\u00a0"),S.push({S:"span",O:"iv-card-link-icon"}));return{S:"div",vI:p,j:I,A:S}},wbV=function(r){var p;
(p=r)&&!(p=r.length>1?r.charAt(0)==="/"&&r.charAt(1)!=="/":r==="/")&&(p=r.replace(/^(https?:)?\/\//,"").split("/",1),p=!p||p.length<1||!p[0]?[]:p[0].toLowerCase().split(".").reverse(),p=p[0]==="com"&&p[1]==="youtube"||p[0]==="be"&&p[1]==="youtu");return p?r.indexOf("/redirect?")===-1:!1},ftR=function(r,p){return p?p:wbV(r)?"current":"new"},L3=function(r,p,I,S,a,B,N){r.context.W.listen(p,"click",v=>{r.Xu(I,S,a,B||[],N||0,v)});
r.context.W.listen(p,"touchstart",()=>{r.QJ=!1});
r.context.W.listen(p,"touchmove",()=>{r.QJ=!0})},GNA=function(r){if(g.m(r,g.E0)?.url)return g.m(r,g.E0).url;
if((r=g.m(r,g.fe))&&r.videoId){let p="/watch?v="+r.videoId;r.playlistId&&(p+="&list="+r.playlistId);r.index&&(p+="&index="+r.index);r.startTimeSeconds&&(p+="&t="+r.startTimeSeconds);return p}return null},R_=function(r,p,I){return{WQ:(r.impressionLoggingUrlsV2s||[]).map(S=>S.baseUrl||""),
click:(I.loggingUrls||[]).map(S=>S.baseUrl||""),
close:(p.dismissLoggingUrlsV2s||[]).map(S=>S.baseUrl||""),
eM:(p.impressionLoggingUrlsV2s||[]).map(S=>S.baseUrl||""),
dY:(p.clickLoggingUrlsV2s||[]).map(S=>S.baseUrl||"")}},$Z=function(r,p){if(p.onClickCommand&&g.m(p.onClickCommand,g.qut)?.targetId==="engagement-panel-error-corrections"){r.L=p;
var I=!0}else I=!1;if(!I||oYn(r,p))if(I=q3R(r,p)){var S={H0:p,bG:I.element,Y8:!1};if(p.onClickCommand)r.V.X("web_infocards_teaser_show_logging_fix")&&(r.p7||ZxY(r),r6(r,p.id),I=r.findLastIndex(S),g.Or(r.cards,I,0,S));else{r.isInitialized||MBr(r);r6(r,p.id);const a=r.findLastIndex(S);g.Or(r.cards,a,0,S);I.Ik(r.U,a);r.wM()}p.autoOpen?r.addCueRange(p.startMs,0x8000000000000,p.id,()=>{r.Z||(r.W=S,pN(r),kNY(r,S),Is(r,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(I=r.context.V.getCurrentTime()*1E3,I<5E3&&I>p.startMs&&
cP1(r,S),r.addCueRange(p.startMs,p.startMs+1,p.id,()=>{cP1(r,S)}),pN(r))}},i9=function(r){r.Z&&(r.Yu.hide(),r.hG.U(),g.ee(r.context.V.getRootNode(),g.yj.IV_DRAWER_OPEN),r.Z=!1,o_(r.V),r.J&&r.J.stop(),r.J=new g.pa(()=>{r.e_&&(r.e_.focus(),r.e_=null)},330),r.J.start())},gYR=function(r,p){p=p.data;
p.autoOpenMs&&r.addCueRange(p.autoOpenMs,0x8000000000000,"",()=>{Is(r,"YOUTUBE_DRAWER_AUTO_OPEN")});
p.autoCloseMs&&r.addCueRange(p.autoCloseMs,0x8000000000000,"",()=>{i9(r)});
const I=p.headerText;g.Xa(r.T5,I);r.C&&(r.V.X("player_tooltip_data_title_killswitch")?r.C.setAttribute("title",I):r.C.setAttribute("data-tooltip-title",I));p.eventId&&(r.eventId=p.eventId);r.dM=g.Vb(p.trackingParams);r.D=g.Vb(p.closeTrackingParams);r.GI=g.Vb(p.iconTrackingParams)},SW=function(r,p,I){let S=-1,a=-1;
for(let B=0;B<r.length;B++){if(r[B].height===p||r[B].width===I)return r[B];((r[B].height||0)<p||(r[B].width||0)<I)&&(S<0||(r[S].height||0)<(r[B].height||0)||(r[S].width||0)<(r[B].width||0))?S=B:((r[B].height||0)>=p||(r[B].width||0)>=I)&&(a<0||(r[a].height||0)>(r[B].height||0)||(r[a].width||0)>(r[B].width||0))&&(a=B)}return r[a>=0?a:S]},as=function(r,p,I,S){return{feature:I.feature?I.feature:"cards",
src_vid:r.context.videoData.videoId,annotation_id:p,ei:r.context.videoData.eventId||"",itct:S.trackingParams||""}},TSr=function(r,p){const I=p.cardId?p.cardId:`cr:${r.K}`;
var S=r.V.G().experiments.bC("enable_error_corrections_infocard_web_client");if(!p.content&&p.teaser.simpleCardTeaserRenderer&&S){S=p.teaser.simpleCardTeaserRenderer;var a=p.icon?p.icon.infoCardIconRenderer:null;if(S.channelAvatar&&S.channelAvatar.thumbnails&&S.channelAvatar.thumbnails.length>0)var B=SW(S.channelAvatar.thumbnails,22,22).url;p={id:I,timestamp:r.K,type:"simple",teaserText:g.Jh(S.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),
autoOpen:!!p.autoOpen,sessionData:{},sponsored:!1,uf:{},Dm:null,ju:S.trackingParams?g.Vb(S.trackingParams):null,GI:a&&a.trackingParams?g.Vb(a.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Bd:null,title:"",customMessage:"",url:null,onClickCommand:S.onTapCommand||null,Nm:B};$Z(r,p)}else if(p.content?.simpleCardContentRenderer){if(!p.cueRanges.length)return;B=p.content?.simpleCardContentRenderer;S=p.teaser.simpleCardTeaserRenderer;a=p.icon?p.icon.infoCardIconRenderer:null;p={id:I,
timestamp:r.K,type:"simple",teaserText:g.Jh(S.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:as(r,I,p,B),sponsored:!1,uf:R_(B,S,B.command),Dm:B.trackingParams?g.Vb(B.trackingParams):null,ju:S.trackingParams?g.Vb(S.trackingParams):null,GI:a&&a.trackingParams?g.Vb(a.trackingParams):null,imageUrl:SW(B.image.thumbnails,290,290).url,displayDomain:B.displayDomain?g.Jh(B.displayDomain):null,showLinkIcon:!!B.showLinkIcon,
Bd:null,title:B.title?g.Jh(B.title):"",customMessage:B.callToAction?g.Jh(B.callToAction):"",url:g.m(B.command,g.E0).url?Fs({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:g.m(B.command,g.E0).url}):null,onClickCommand:null};$Z(r,p)}else if(p.content?.collaboratorInfoCardContentRenderer){if(!p.cueRanges.length)return;B=p.content?.collaboratorInfoCardContentRenderer;S=p.teaser.simpleCardTeaserRenderer;a=p.icon?p.icon.infoCardIconRenderer:null;p={id:I,timestamp:r.K,type:"collaborator",
teaserText:g.Jh(S.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:as(r,I,p,B),sponsored:!1,uf:R_(B,S,B.endpoint),Dm:B.trackingParams?g.Vb(B.trackingParams):null,ju:S.trackingParams?g.Vb(S.trackingParams):null,GI:a&&a.trackingParams?g.Vb(a.trackingParams):null,channelId:g.m(B.endpoint,g.wC).browseId,customMessage:B.customText?g.Jh(B.customText):null,profileImageUrl:SW(B.channelAvatar.thumbnails,290,
290).url,title:B.channelName?g.Jh(B.channelName):"",metaInfo:[B.subscriberCountText?g.Jh(B.subscriberCountText):""],url:Fs({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:g.m(B.endpoint,g.wC).canonicalBaseUrl?g.m(B.endpoint,g.wC).canonicalBaseUrl:`/channel/${g.m(B.endpoint,g.wC).browseId}`}),onClickCommand:null};$Z(r,p)}else if(p.content?.playlistInfoCardContentRenderer){if(!p.cueRanges.length)return;B=p.content?.playlistInfoCardContentRenderer;S=p.teaser.simpleCardTeaserRenderer;
a=p.icon?p.icon.infoCardIconRenderer:null;p={id:I,timestamp:r.K,type:"playlist",teaserText:g.Jh(S.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:as(r,I,p,B),sponsored:!1,uf:R_(B,S,B.action),Dm:B.trackingParams?g.Vb(B.trackingParams):null,ju:S.trackingParams?g.Vb(S.trackingParams):null,GI:a&&a.trackingParams?g.Vb(a.trackingParams):null,z4:SW(B.playlistThumbnail.thumbnails,258,290).url,customMessage:B.customMessage?
g.Jh(B.customMessage):null,playlistVideoCount:g.Jh(B.playlistVideoCount),title:B.playlistTitle?g.Jh(B.playlistTitle):"",metaInfo:[B.channelName?g.Jh(B.channelName):"",B.videoCountText?g.Jh(B.videoCountText):""],url:Fs({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:GNA(B.action)}),onClickCommand:null};$Z(r,p)}else if(p.content?.videoInfoCardContentRenderer){if(!p.cueRanges.length)return;B=p.content?.videoInfoCardContentRenderer;S=p.teaser.simpleCardTeaserRenderer;a=p.icon?
p.icon.infoCardIconRenderer:null;p={id:I,timestamp:r.K,type:"video",teaserText:g.Jh(S.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:as(r,I,p,B),sponsored:!1,uf:R_(B,S,B.action),Dm:B.trackingParams?g.Vb(B.trackingParams):null,ju:S.trackingParams?g.Vb(S.trackingParams):null,GI:a&&a.trackingParams?g.Vb(a.trackingParams):null,z4:SW(B.videoThumbnail.thumbnails,258,290).url,videoDuration:B.lengthString?
g.Jh(B.lengthString):null,customMessage:B.customMessage?g.Jh(B.customMessage):null,title:B.videoTitle?g.Jh(B.videoTitle):"",metaInfo:[B.channelName?g.Jh(B.channelName):"",B.viewCountText?g.Jh(B.viewCountText):""],isLiveNow:!!B.badge,url:Fs({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:GNA(B.action)}),onClickCommand:null};$Z(r,p)}r.K++},KtC=function(r,p){return g.rP(r.cards,I=>I.H0.id===p)},pN=function(r){g.K(r.V.getRootNode(),"ytp-cards-shopping-active",QAu(r))},r6=function(r,
p){if(p=KtC(r,p))p===r.W&&(r.W=null),r.V.removeCueRange(p.H0.id),g.s3(p.bG),g.N5(r.cards,p),r.wM(),pN(r)},Is=function(r,p,I){if(!r.Z){r.Yu.show();
r.HI=new g.pa(()=>{g.NL(r.context.V.getRootNode(),g.yj.IV_DRAWER_OPEN)},0);
r.HI.start();r.hG.B(r.U,"mousewheel",a=>{r.UD.start();a.preventDefault();a=a||window.event;let B=0;a.type=="MozMousePixelScroll"?B=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?B=a.detail:B=a.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=B)r.U.scrollTop+=a});
r.Z=!0;var S=g.oV();S&&r.dM&&r.D&&g.$2(S,[r.dM,r.D]);p={TRIGGER_TYPE:p};for(const a of r.cards)a.Y8||(a.Y8=!0,EYY(r.context.logger,a.H0.uf.WQ,p)),S&&g.$2(S,[a.H0.Dm]);o_(r.V);I&&(r.J=new g.pa(()=>{r.e_=r.C;r.sD.focus()},330),r.J.start())}},MBr=function(r){g.vX(r.wu(),[g.yj.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.EX(r.V,r.N,5);r.Hb();r.C=g.L2("ytp-cards-button",r.V.getRootNode());r.sD=g.L2("iv-drawer-close-button",r.N);r.isInitialized=!0},ZxY=function(r){r.iC.push(g.ST("iv-teaser-shown",r.H6,r));
r.iC.push(g.ST("iv-teaser-hidden",r.We,r));r.iC.push(g.ST("iv-teaser-clicked",r.hL,r));r.p7=!0},oYn=function(r,p){r.L=p;
var I=r.V.getVideoData();if(!I)return!1;I=g.S7(I);if(I?.markersMap)for(let a=0;I?.markersMap.length>a;a++){var S=I?.markersMap[a];if(S.key==="ERROR_CORRECTION_MARKERS"&&(S=S.value?.markers)&&S.length>0)return p.startMs=g.m(S[0],g.F9F)?.timeRangeStartMillis||0,r.L=null,!0}return!1},q3R=function(r,p){switch(p.type){case "simple":r=r.WI;
var I=p.displayDomain?{S:"div",O:"iv-card-image-text",uC:p.displayDomain}:void 0;var S=VBY(p);I={S:"div",vI:["iv-card"],A:[{S:"a",O:"iv-click-target",j:{href:p.url?p.url.W()||"":""},A:[Uu(p.imageUrl,I),{S:"div",O:"iv-card-content",A:[PE("h2",void 0,p.title),S]}]}]};I=new g.H(I);HE(r,g.n2("iv-click-target",I.element),p,p.url);p=I;break;case "collaborator":r=r.WI;I={S:"div",vI:["iv-card","iv-card-channel"],A:[{S:"a",vI:["iv-click-target"],j:{href:p.url.W()||"","data-ytid":p.channelId},A:[Uu(p.profileImageUrl),
{S:"div",O:"iv-card-content",A:[n3(p),{S:"h2",O:"iv-card-primary-link",uC:p.title},Ap(p)]}]}]};I=new g.H(I);HE(r,g.n2("iv-click-target",I.element),p,p.url);p=I;break;case "playlist":r=r.WI;I={S:"div",vI:["iv-card","iv-card-playlist"],A:[{S:"a",O:"iv-click-target",j:{href:p.url.W()||""},A:[Uu(p.z4,{S:"div",O:"iv-card-image-overlay",A:[{S:"span",O:"iv-card-playlist-video-count",uC:p.playlistVideoCount}]}),{S:"div",O:"iv-card-content",A:[n3(p),PE("h2","iv-card-primary-link",p.title),Ap(p)]}]}]};I=new g.H(I);
HE(r,g.n2("iv-click-target",I.element),p,p.url);p=I;break;case "productListing":r=r.WI;var a=p.offers.length!=0;I=["iv-card"];S="";var B=VBY(p);a&&(I.push("iv-card-product-listing"),S="iv-card-primary-link",B=p.offers[0],a=[],B.price&&a.push({S:"div",O:"iv-card-offer-price",uC:B.price}),B.merchant&&a.push({S:"div",O:"iv-card-offer-merchant",uC:B.merchant}),B={S:"div",A:a});a=p.url?p.url.W()||"":"";I={S:"div",vI:I,j:{tabindex:"0"},A:[{S:"a",vI:["iv-card-image","iv-click-target"],j:{style:"background-image: url("+
p.imageUrl+");",href:a,"aria-hidden":"true",tabindex:"-1"}},{S:"div",O:"iv-card-content",A:[p.sponsored?{S:"div",O:"iv-card-sponsored",A:["Sponsored",{S:"div",O:"iv-ad-info-container",A:[{S:"div",O:"iv-ad-info",uC:"{{adInfo}}"},{S:"div",O:"iv-ad-info-icon-container",A:[{S:"div",O:"iv-ad-info-icon"},{S:"div",O:"iv-ad-info-callout"}]}]}]}:"",{S:"a",O:"iv-click-target",j:{href:a},A:[PE("h2",S,p.title),B]}]}]};I=new g.H(I);S=g.vb("span");g.Xa(S,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
I.setContent(S,"adInfo");HE(r,g.n2("iv-click-target",I.element),p,p.url);p=I;break;case "video":r=r.WI;I=p.isLiveNow?{S:"span",vI:["yt-badge","yt-badge-live"],uC:"LIVE NOW"}:null;I={S:"div",vI:["iv-card","iv-card-video"],A:[{S:"a",O:"iv-click-target",j:{href:p.url?.W()||""},A:[Uu(p.z4,p.videoDuration?{S:"span",O:"iv-card-video-duration",uC:p.videoDuration}:void 0),{S:"div",O:"iv-card-content",A:[n3(p),PE("h2","iv-card-primary-link",p.title),Ap(p),I]}]}]};I=new g.H(I);HE(r,g.n2("iv-click-target",I.element),
p,p.url);p=I;break;default:return null}return p},cP1=function(r,p){if(!g.BX(r.V.getRootNode(),"ytp-cards-teaser-shown")){if(r.W!==p){var I=g.oV(),S=r.W?r.W.H0.GI:r.GI;
I&&S&&g.iz(I,[S]);r.W=p;pN(r)}(I=r.isInitialized&&r.wu().style.display=="none")||(I=r.context.V.getPlayerState(),S=I===0&&r.context.V.getCurrentTime()===0,I=!(I===1||I===3||S));I||p.H0.teaserDurationMs&&r.V.z_(!0,{teaserText:p.H0.teaserText,durationMs:p.H0.teaserDurationMs,onClickCommand:p.H0.onClickCommand,Nm:p.H0.Nm??null});r.Lg.isActive()||((!r.Z||!r.UD.isActive()&&r.z$)&&kNY(r,p),r.Lg.start(910+p.H0.teaserDurationMs))}},QAu=function(r){return r.W?r.W.H0.type==="productListing":r.V.X("enable_wn_infocards")?
!!r.cards?.length&&g.LT(r.cards,p=>p.H0.type==="productListing"):g.LT(r.cards,p=>p.H0.type==="productListing")},kNY=function(r,p){r.Y.ez?(p=new cE([0,
r.U.scrollTop],[0,p.bG.offsetTop],600,pbn),r.context.Z.listen(p,"animate",I=>{r.U.scrollTop=I.y}),r.context.Z.listen(p,"finish",I=>{r.U.scrollTop=I.y}),p.play()):(r.Y.G5(!0),r.U.scrollTop=p.bG.offsetTop,r.Y.G5(!1))},Bw=function(r){return r.W&&r.W.H0?r.W.H0:r.cards[0]&&r.cards[0].H0?r.cards[0].H0:null},jAV=function(r){const p=r.annotation.data;
"start_ms"in p&&"end_ms"in p&&r.addCueRange(Number(p.start_ms),Number(p.end_ms),r.annotation.id,()=>{r.show()},()=>{r.hide()})},tBP=function(r,p){var I=UeY(p).width;
g.YY(p,I);I=new TF(p,[I,p.offsetTop],[I-I,p.offsetTop],200,rPA);g.Z(r,I);r.context.Z.listen(I,"begin",()=>{g.rD(p,!0)});
I.play()},Nz=function(r,p,I){I.stopPropagation();
DmU(r);h1C(r,p);r.W.focus()},xma=function(r){const p=r.annotation.data;
if(r.annotation.style==="cta")var I=6;else if(r.annotation.style==="video"||r.annotation.style==="playlist")I=7;r.J=p.collapsedelay_ms||r.J;const S=["iv-promo","iv-promo-inactive"];r.wu().setAttribute("aria-hidden","true");r.wu().setAttribute("aria-label","Promotion");r.wu().tabIndex=0;const a=r.annotation.A_();let B;var N=p.image_url;N&&(B=r.createElement({S:"div",vI:["iv-promo-img","iv-click-target"]}),N=r.createElement({S:"img",j:{src:N,"aria-hidden":"true"}}),B.appendChild(N),p.video_duration&&
!p.is_live?(N=r.createElement({S:"span",O:"iv-promo-video-duration",uC:p.video_duration}),B.appendChild(N)):p.playlist_length&&(N=r.createElement({S:"span",O:"iv-promo-playlist-length",uC:p.playlist_length.toString()}),B.appendChild(N)),a&&L3(r,B,a,r.annotation.id,p.session_data,void 0,I));a?(N=r.createElement({S:"a",O:"iv-promo-txt"}),g.zV(N,a.W()),r.W=N):r.W=r.createElement({S:"div",O:"iv-promo-txt"});let v,e,C,b;switch(r.annotation.style){case "cta":case "website":v=r.createElement({S:"p",A:[{S:"strong",
uC:p.text_line_1}]});e=r.createElement({S:"p",A:[{S:"span",O:"iv-promo-link",uC:p.text_line_2}]});if(N=p.text_line_3)S.push("iv-promo-website-card-cta-redesign"),C=r.createElement({S:"button",vI:["iv-promo-round-expand-icon","ytp-button"]}),N=r.createElement({S:"button",vI:["iv-button","iv-promo-button"],A:[{S:"span",O:"iv-button-content",uC:N}]}),b=r.createElement({S:"div",O:"iv-promo-button-container"}),b.appendChild(N),a&&L3(r,r.wu(),a,r.annotation.id,p.session_data,void 0,I);g.NL(r.W,"iv-click-target");
a&&L3(r,r.W,a,r.annotation.id,p.session_data,void 0,I);break;case "playlist":case "video":v=r.createElement({S:"p",A:[{S:"span",uC:p.text_line_1}]}),e=r.createElement({S:"p",A:[{S:"strong",uC:p.text_line_2}]}),p.is_live&&(v=e,e=r.createElement({S:"span",vI:["yt-badge","iv-promo-badge-live"],uC:"LIVE NOW"})),g.NL(r.W,"iv-click-target"),a&&L3(r,r.W,a,r.annotation.id,p.session_data,void 0,I),S.push("iv-promo-video")}v&&r.W.appendChild(v);e&&r.W.appendChild(e);r.K.appendChild(r.W);b&&r.K.appendChild(b);
I=r.createElement({S:"div",O:"iv-promo-actions"});r.U=r.createElement({S:"button",vI:["iv-promo-expand","ytp-button"]});r.U.title="Expand";r.context.W.listen(r.U,"click",J=>{Nz(r,5E3,J)});
I.appendChild(r.U);g.rD(r.U,!1);r.context.W.listen(r.wu(),"mouseover",r.UD,r);r.context.W.listen(r.wu(),"mouseout",r.WI,r);r.context.W.listen(r.wu(),"touchend",J=>{Nz(r,5E3,J)});
r.Z=r.createElement({S:"button",vI:["iv-promo-close","ytp-button"]});r.Z.title="Close";r.context.W.listen(r.Z,"click",r.annotation.style==="cta"&&p.text_line_3?r.L:r.iC,r);I.appendChild(r.Z);g.vX(r.wu(),S);B&&(g.Cx(r.wu(),B),C&&B.appendChild(C));g.Cx(r.wu(),r.K);g.Cx(r.wu(),I)},vw=function(r){r.N&&(g.OK.clearTimeout(r.N),r.N=null)},DmU=function(r){r.C.stop();
r.isCollapsed&&(g.Ca(r.wu(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),r.isCollapsed=!1,r.W&&r.W.removeAttribute("aria-hidden"),g.rD(r.U,!1),g.rD(r.Z,!0))},h1C=function(r,p){r.N||(r.N=g.eE(function(){vw(this);
z1g(this)},p,r))},z1g=function(r){r.isCollapsed||r.D||r.N||(g.NL(r.wu(),"iv-promo-collapsed"),r.isCollapsed=!0,r.C.start())},EYY=function(r,p,I){p&&(I?eW(r,p.map(S=>g.jt(S,I))):eW(r,p))},eW=function(r,p,I,S){let a=1,B=void 0,N=-1;
if(I){let v=!1;B=()=>{a--;a||v||(clearTimeout(N),v=!0,I())};
N=setTimeout(()=>{v=!0;I()},1E3)}for(const v of p||[])a++,g.Ym(v,B);
S&&(a++,S!==0&&r.V.sendVideoStatsEngageEvent(S,B))},mmu=function(r){return r==="annotation-editor"||r==="live-dashboard"},uau=function(r){r.N&&(r.player.removeEventListener("videodatachange",r.N),r.N=null)},lt1=function(r){r=r.createElement({S:"div",
vI:["annotation","annotation-type-custom"]});g.rD(r,!1);return r},b9=function(r,p){var I=!1,S=p.getElementsByTagName("annotations");
if(S&&!(S.length<1)&&(S=S[0].getAttribute("itct"))){var a=g.oV();if(a){var B=g.GJ();B&&g.gg(g.Un)(void 0,a,B,[g.Vb(S)])}}p=p.getElementsByTagName("annotation");for(S=0;S<p.length;S++){var N=Y3U(r,p[S]);a=null;try{a:{if(!N){a=null;break a}var v=N.id;B=/.+/;const X=typeof v==="string"&&B!=null&&v!=null&&v.match(B)?v:"",d=YJ(N.type,FtA),M=YJ(N.style,UmC),T=bxV(N.data),E=T.length!==0?JSON.parse(T):{};b:{var e=N.action;B=yPY;if(e==null){var C=null;break b}if(g.qK(e)){N=[];for(const D of e){const z=B(D);
z&&N.push(z)}C=N;break b}const Q=B(e);C=Q?[Q]:[]}B=C;a=X&&d?new PiY(X,d,M,B,E):null}}catch(X){}if(a)if(a.type==="branding"||a.type==="promotion"){B=r;N=a;var b=lt1(B),J=null;switch(N.type){case "branding":if(B.player.G().kE)break;B.player.X("web_player_overlay_positioned_layout")?(b.setAttribute("data-overlay-order","11"),B.player.Fv(b,4,!0)):B.U.element.appendChild(b);J=new nYU(b,CN(B),N);break;case "promotion":g.EX(B.player,b,4),J=new APa(b,CN(B),N)}J&&J.rM();if(B=J)g.Z(r,B),r.J[a.id]=B}else if(a.type===
"card"||a.type==="drawer"){r.W||(r.W=HxP(r),g.Z(r,r.W));if(a.type==="card"){b=r.W;var W=(I=a)&&I.data&&I.data.card_type;a=I.data;if(W)switch(B=a.tracking||{},B={WQ:B.impression,click:B.click,close:B.close,eM:B.teaser_impression,dY:B.teaser_click},N=a.tracking_params||{},J=null,W){case "collaborator":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||
!1,uf:B,Dm:N.card?g.Vb(N.card):null,ju:N.teaser?g.Vb(N.teaser):null,GI:N.icon?g.Vb(N.icon):null,channelId:a.channel_id,customMessage:a.custom_message?a.custom_message:null,profileImageUrl:a.image_url,title:a.title,metaInfo:a.meta_info,url:Fs({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),onClickCommand:null};$Z(b,I);break;case "playlist":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,
autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,uf:B,Dm:N.card?g.Vb(N.card):null,ju:N.teaser?g.Vb(N.teaser):null,GI:N.icon?g.Vb(N.icon):null,z4:a.image_url,playlistVideoCount:a.playlist_video_count,customMessage:a.custom_message?a.custom_message:null,title:a.title,metaInfo:a.meta_info,url:Fs({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),onClickCommand:null};$Z(b,I);break;case "productListing":a.signin_url&&(J=Fs({target:"current",
value:a.signin_url}));W=[];const X=a.offers||[];for(let d=0;d<X.length;d++)W.push(new Ltr(g.va(X[d].merchant),g.va(X[d].price)));I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,uf:B,Dm:N.card?g.Vb(N.card):null,ju:N.teaser?g.Vb(N.teaser):null,GI:N.icon?g.Vb(N.icon):null,imageUrl:a.image_url,displayDomain:a.display_domain?a.display_domain:
null,showLinkIcon:!!a.show_link_icon,Bd:a.button_icon_url?a.button_icon_url:null,title:a.title,customMessage:a.custom_message?a.custom_message:null,url:Fs({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),ywE:J,h9u:a.signin_title?a.signin_title:void 0,z9u:a.signin_message?a.signin_message:void 0,offers:W,onClickCommand:null};$Z(b,I);break;case "simple":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,
startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,uf:B,Dm:N.card?g.Vb(N.card):null,ju:N.teaser?g.Vb(N.teaser):null,GI:N.icon?g.Vb(N.icon):null,imageUrl:a.image_url,displayDomain:a.display_domain?a.display_domain:null,showLinkIcon:!!a.show_link_icon,Bd:a.button_icon_url?a.button_icon_url:null,title:a.title,customMessage:a.custom_message?a.custom_message:null,url:Fs({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),onClickCommand:null};
$Z(b,I);break;case "video":I={id:I.id,timestamp:a.timestamp||0,type:a.card_type,teaserText:a.teaser_text,teaserDurationMs:a.teaser_duration_ms,startMs:a.start_ms,autoOpen:a.auto_open||!1,sessionData:a.session_data||{},sponsored:a.sponsored||!1,uf:B,Dm:N.card?g.Vb(N.card):null,ju:N.teaser?g.Vb(N.teaser):null,GI:N.icon?g.Vb(N.icon):null,z4:a.image_url,videoDuration:a.video_duration||null,customMessage:a.custom_message?a.custom_message:null,title:a.title,metaInfo:a.meta_info,isLiveNow:!!a.is_live_now,
url:Fs({pause_on_navigation:a.pause_on_navigation,target:a.target||"new",value:a.url}),onClickCommand:null},$Z(b,I)}}else gYR(r.W,a);I=!0}}I&&(o_(r.player),r.Y())},R1R=function(r){const p=r.player.G();
r=r.player.getVideoData();return(p.annotationsLoadPolicy||r.annotationsLoadPolicy)===1&&!r.nQ||p.dM.get(r.videoId)||r.uV()||g.$0(r)?!0:!1},ryU=function(r,p){p=!p.isCued()&&!p.W(1024);
r.U.G5(p);r.Z.G5(p)},ilU=function(r,p){const I=p.videoId;
var S=B=>{var N=r.loadNumber;r.K=null;r.loaded&&r.loadNumber===N&&r.player.getVideoData().videoId===I&&(B=g.D3(B)&&B.responseXML?B.responseXML:null)&&(b9(r,B),g.NL(r.player.getRootNode(),"iv-module-loaded"))};
g.cM()&&(S=px5(r,S));const a={format:"XML",onFinish:S,onError:()=>{r.K=null},
urlParams:{}};p.isPharma&&(a.urlParams.pharma="1");a.method="POST";a.withCredentials=!0;(S=r.player.G().dM.get(I))&&IsP(a,S);S=S&&S.Te;if(!p.Gi||S)r.N=()=>{if(!r.L)r.onVideoDataChange(a);const B=r.player.getVideoData();B?.Ch()&&!r.iC&&$k1(r,B)},r.player.addEventListener("videodatachange",r.N)},Jw=function(r,p){var I=!1;
r.W||(r.W=HxP(r),g.Z(r,r.W));for(var S of p.cards||[])S.cardRenderer&&(TSr(r.W,S.cardRenderer),I=!0);I&&(r.player.getVideoData()?.Ch()||(I=r.W,S=p.headerText?g.Jh(p.headerText):"",g.Xa(I.T5,S),I.C&&(I.V.X("player_tooltip_data_title_killswitch")?I.C.setAttribute("title",S):I.C.setAttribute("data-tooltip-title",S)),I.context.videoData.eventId&&(I.eventId=I.context.videoData.eventId),I.dM=p.trackingParams?g.Vb(p.trackingParams):null,I.D=p.closeButton.infoCardIconRenderer.trackingParams?g.Vb(p.closeButton.infoCardIconRenderer.trackingParams):
null,I.GI=p.icon.infoCardIconRenderer.trackingParams?g.Vb(p.icon.infoCardIconRenderer.trackingParams):null,r.Y()),o_(r.player))},$k1=function(r,p){if(p=p.getWatchNextResponse()?.cards?.cardCollectionRenderer)r.iC=!0,Jw(r,p),p.headerText&&r.CS&&(p=g.Jh(p.headerText),r.player.X("player_tooltip_data_title_killswitch")?r.CS.setAttribute("title",p):r.CS.setAttribute("data-tooltip-title",p))},px5=function(r,p){return(...I)=>{r.Cg()||r.rM.push(g.Y_.a4(()=>{p(...I)}))}},IsP=function(r,p){r.method="POST";
r.postParams=r.postParams||{};p.Te&&(r.postParams.ic_coll=p.Te);p.PW&&(r.postParams.ic_track=p.PW)},Y3U=function(r,p){const I={};
for(var S of p.attributes)I[S.name]=S.nodeValue;for(S=0;S<p.childNodes.length;S++){var a=p.childNodes[S];if(!g.MK(a)||a.nodeType!=1)continue;var B=void 0;if(I[a.tagName])B=I[a.tagName];else if(a.tagName==="data"){a.childNodes.length>0&&(B=a.childNodes[0].nodeValue,I[a.tagName]=typeof B==="string"?B.trim():B);continue}else B=[],I[a.tagName]=B;a&&a.tagName==="TEXT"?a.childNodes.length===1&&a.childNodes[0].nodeType===3?B.push(a.childNodes[0].nodeValue):B.push(""):a&&B.push(Y3U(r,a))}return I},CN=function(r){if(!r.D){const p=
new SGY(r);
g.Z(r,p);const I=new g.sj(r);g.Z(r,I);r.D=new asR(p,I,r.player.G(),r.player.getVideoData(),r.logger,r.player,r.KL)}return r.D},BDY=function(r){const p=r.player.getVideoData();
if(p.r$){var I=r.player.G().dM.get(p.videoId);if(I){var S={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(a,B,N)=>{a=r.loadNumber;B=p.videoId;r.loaded&&r.loadNumber===a&&r.player.getVideoData().videoId===B&&(N=g.D3(N)&&N.responseXML?N.responseXML:null)&&b9(r,N)}};
g.cM()&&(S.onFinish=px5(r,S.onFinish));S.postParams={ic_only:"1"};IsP(S,I);r.L=!0;g.AW(p.r$,S)}}},HxP=function(r){const p=new g.H({S:"div"});
g.rD(p.element,!1);const I=new NDV(r.player,p.element,CN(r));g.Z(I,p);p.Ik(r.U.element);I.rM();return I},vMV=function(r,p,I,S,a){if(!r.player.G().kE){var B=[];
p.navigationEndpoint&&g.m(p.navigationEndpoint,g.wC)&&g.m(p.navigationEndpoint,g.wC).browseId&&B.push(new Ox1("openUrl","click",new sAY(`/channel/${g.m(p.navigationEndpoint,g.wC).browseId}`,"new",!0,!0)));var N=p.watermark.thumbnails[0];S={channel_name:p.channelName,end_ms:p.endTimeMs,image_height:N.height,image_type:1,image_url:N.url,image_width:N.width,is_mobile:!1,session_data:{annotation_id:I,ei:a,feature:"iv",itct:p.trackingParams,src_vid:S},start_ms:p.startTimeMs};if(p.subscribeButton&&g.m(p.subscribeButton,
g.Qg)){S.channel_id=g.m(p.subscribeButton,g.Qg).channelId;p=g.m(p.subscribeButton,g.Qg);N=a=null;p.subscribed?(p.subscriberCountWithUnsubscribeText&&(a=g.Jh(p.subscriberCountWithUnsubscribeText)),p.subscriberCountText&&(N=g.Jh(p.subscriberCountText))):(p.subscriberCountText&&(a=g.Jh(p.subscriberCountText)),p.subscriberCountWithSubscribeText&&(N=g.Jh(p.subscriberCountWithSubscribeText)));const v=g.m(p.signInEndpoint?.commandMetadata,g.Zx)?.url||"";p={subscribeText:g.Jh(p.unsubscribedButtonText),subscribeCount:a||
"",unsubscribeText:g.Jh(p.subscribedButtonText),unsubscribeCount:N||"",enabled:p.enabled||!1,classic:!1,subscribed:p.subscribed||!1,feature:"iv",signInUrl:v};S.standalone_subscribe_button_data=p}B=new PiY(I,"branding","branding",B,S);S=lt1(r);r.player.X("web_player_overlay_positioned_layout")?(S.setAttribute("data-overlay-order","11"),r.player.Fv(S,4,!0)):r.U.element.appendChild(S);B=new nYU(S,CN(r),B);B.rM();g.Z(B,B);r.J[I]=B}};
g.XG.prototype.z_=g.$9(36,function(r,p){const I=g.Fc(this.NT());I&&I.z_(r,p)});
var MC={},Z2=null;g.EK(cE,g.JZ);g.q=cE.prototype;g.q.getDuration=function(){return this.duration};
g.q.play=function(r){if(r||this.W==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;kJ(this);this.startTime=r=g.TB();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.N=this.startTime;this.progress||this.VC();this.Ri("play");this.isPaused()&&this.Ri("resume");this.W=1;const p=g.k9(this);p in MC||(MC[p]=this);AgU();H2P(this,r);return!0};
g.q.stop=function(r){kJ(this);this.W=0;r&&(this.progress=1);LQa(this,this.progress);this.onStop();this.uP()};
g.q.pause=function(){this.isPlaying()&&(kJ(this),this.W=-1,this.Ri("pause"))};
g.q.mE=function(){this.W==0||this.stop(!1);this.Ri("destroy");cE.kY.mE.call(this)};
g.q.destroy=function(){this.dispose()};
g.q.m1=function(){this.Ri("animate")};
g.q.Ri=function(r){this.dispatchEvent(new ROY(r,this))};
g.EK(ROY,g.Cp);g.EK(g8,cE);g8.prototype.Z=function(){};
g8.prototype.m1=function(){this.Z();g8.kY.m1.call(this)};
g8.prototype.uP=function(){this.Z();g8.kY.uP.call(this)};
g8.prototype.VC=function(){this.Z();g8.kY.VC.call(this)};
g.EK(TF,g8);TF.prototype.Z=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var SGY=class extends g.AQ{constructor(r){super();this.U=r||window;this.W=[]}listen(r,p,I,S){I=(0,g.c5)(I,S||this.U);r=g.$X(r,p,I);this.W.push(r);return r}CK(r,p,I,S){I=(0,g.c5)(I,S||this.U);r=PpY(r,p,I);this.W.push(r);return r}Pe(r){g.id(r);g.N5(this.W,r)}removeAll(){g.id(this.W);this.W.length=0}mE(){this.removeAll();super.mE()}};var sPa=class extends g.z${constructor(r){super(r);this.N=this.endscreen=null;this.U={};this.J={};this.C=this.Z=null;this.D=[];this.W=null;this.iC=!0;this.K=0;r=r.G();this.Y=g.Jd(r)||g.Oh(r);this.events=new g.oM(this);g.Z(this,this.events);this.events.B(this.player,g.c7("creatorendscreen"),this.onCueRangeEnter);this.events.B(this.player,g.g_("creatorendscreen"),this.onCueRangeExit);this.events.B(this.player,"resize",this.QH);this.events.B(window,"focus",this.L);this.load();const p=g.vb("STYLE");(g.Pa("HEAD")[0]||
document.body).appendChild(p);this.addOnDisposeCallback(()=>{g.s3(p)});
p.sheet&&(p.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),p.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!j2(this)){var r=g.Dhh(this.player.getVideoData());r?(r=Eu(r,$mY(this)),tp(this,r,!1)):BSY(this)}}unload(){tp(this,null);this.N&&(this.N.abort(),this.N=null);super.unload()}kN(r,p){return j2(this)?r==="loadCustomEndscreenRenderer"?(r=Eu(p,"new"),tp(this,r),!0):null:null}getOptions(){return j2(this)?["loadCustomEndscreenRenderer"]:[]}QH(){if(this.endscreen&&this.endscreen.elements){var r=this.player.getVideoContentRect();if(r&&r.width!==0&&r.height!==0){var p=this.player.getPlayerSize();
if(p&&p.width!==0&&p.height!==0){var I=r.width/r.height;var S=0;var a=-1;for(var B=0;B<eau.length;B++){var N=Math.abs(p.width-eau[B]);if(a===-1||S>=N)a=B,S=N}S=C1R[a];this.Z&&g.tP(this.Z.element,"outline-width",Math.max(p.width,p.height)+"px");for(p=0;p<this.endscreen.elements.length;++p){B=this.endscreen.elements[p].id;a=this.U[B];N=this.J[B];if(!a||!N)continue;const e=N.width*I/N.aspectRatio;var v=Math.round(N.width*r.width);B=Math.round(e*r.height);const C=r.left+Math.round(N.left*r.width),b=r.top+
Math.round(N.top*r.height);g.Lx(a.element,v,B);g.YY(a.element,C,b);g.Ca(a.element,blR);v>256||B>256?g.NL(a.element,"ytp-ce-large-round"):v>96||B>96?g.NL(a.element,"ytp-ce-medium-round"):g.NL(a.element,"ytp-ce-small-round");g.Ca(a.element,Jy5);v=N.left+N.width/2;N=N.top+e/2;g.NL(a.element,v<=.5&&N<=.5?"ytp-ce-top-left-quad":v>.5&&N<=.5?"ytp-ce-top-right-quad":v<=.5&&N>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ca(a.element,C1R);g.NL(a.element,S);(a=g.Ha(document,"div","ytp-ce-expanding-overlay-body",
a.element)[0])&&g.tP(a,"height",`${B}px`)}}}}}onCueRangeEnter(r){if(this.endscreen)if(r.getId()==="ytp-ce-in-endscreen")u3(this,this.endscreen.impressionUrls),(r=g.oV())&&this.endscreen.visualElement&&g.Ik(r,this.endscreen.visualElement),this.W&&(g.NL(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.lf()?g.NL(this.W,"ytp-ce-hide-button-lower"):g.ee(this.W,"ytp-ce-hide-button-lower"));else{r=r.getId().substring(15);var p=this.U[r],I=this.J[r];g.NL(p.element,"ytp-ce-element-show");
p.element.removeAttribute("aria-hidden");p=this.player.getRootNode();g.NL(p,"ytp-ce-shown");u3(this,I.impressionUrls);(p=g.oV())&&g.Ik(p,I.visualElement);this.player.G().D&&g.sX(this.player,"endscreenelementshown",r)}}onCueRangeExit(r){if(r.getId()==="ytp-ce-in-endscreen")this.W&&(g.ee(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{r=r.getId().substring(15);var p=this.U[r];g.ee(p.element,"ytp-ce-element-show");p.element.setAttribute("aria-hidden","true");p=this.player.getRootNode();
g.ee(p,"ytp-ce-shown");this.player.G().D&&g.sX(this.player,"endscreenelementhidden",r)}}L(r){r.target===window&&(new g.pa(()=>{for(const p of Object.values(this.U))g.Ca(p.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}G5(r){for(const p of Object.values(this.U))r?p.element.setAttribute("hidden",""):p.element.removeAttribute("hidden")}kJ(r){this.W&&this.player.getRootNode().removeChild(this.W);
r&&(g.NL(r,"ytp-ce-hide-button-container"),this.W=r,g.EX(this.player,this.W,4))}},eau=[346,426,470,506,570,640,853,1280,1920],C1R="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Jy5=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],blR=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var sAY=class{constructor(r,p,I,S){this.value=r;this.target=p;this.showLinkIcon=I;this.U=S}W(){return this.value?this.value:null}},JPn={Z6:"current",ND:"new"};var Ox1=class{constructor(r,p,I){this.type=r;this.trigger=p;this.url=I}},WtP={CLOSE:"close",Ru:"openUrl",SUBSCRIBE:"subscribe"},XbA={nJ:"click",CLOSE:"close",JI:"hidden",DXu:"rollOut",BMI:"rollOver",Qk$:"shown"};var PiY=class{constructor(r,p,I,S,a){this.id=r;this.type=p;this.style=I;this.data=a;this.action=S||[]}A_(){const r=dmA(this,p=>p.type==="openUrl"&&p.url!=null);
return r?r.url:null}},UmC={jc:"anchored",vN:"branding",CHANNEL:"channel",Un:"cta",Xy:"highlightText",VD:"label",PLAYLIST:"playlist",POPUP:"popup",mTk:"speech",SUBSCRIBE:"subscribe",vEu:"title",VIDEO:"video",rYM:"website"},FtA={vN:"branding",JS:"card",yI:"drawer",tI:"highlight",sf:"marker",guk:"promotion",TEXT:"text",KvC:"widget"};var WA1=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
Xxg=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var Oln=class{constructor(r,p){this.context=r;this.W=p}};var Ltr=class{constructor(r,p){this.merchant=r;this.price=p}};var yyC=class extends g.AQ{constructor(r,p){super();this.element=r;this.context=p;this.QJ=!1;this.Rk=new Map;this.BI=new Map;this.context.V.addEventListener(g.c7("annotations_module"),I=>{(I=this.Rk.get(I))&&I.apply(this)});
this.context.V.addEventListener(g.g_("annotations_module"),I=>{(I=this.BI.get(I))&&I.apply(this)})}addCueRange(r,p,I,S,a){r=new g.Y0(r,p,{id:I,
namespace:"annotations_module"});S&&this.Rk.set(r,S);a&&this.BI.set(r,a);this.context.V.W0([r],1)}rM(){this.context.U.subscribe("resize",this.wM,this)}wu(){return this.element}Xu(r,p,I,S,a,B){if(this.QJ)return!1;B&&(B.stopPropagation(),B.preventDefault());this.navigate(r,I,S,a);return!1}show(){}hide(){}destroy(){g.s3(this.wu())}wM(){}navigate(r,p,I,S){const a=r.W();if(a){var B=ftR(a,r.target),N=()=>{r.U&&this.context.V.pauseVideo();const v=this.context.videoData.Ur||!1,e=g.Gh(a||"");v&&e&&(e.v||e.list)?
this.context.V.zd(e.v,p,e.list,!1):g.IO(a||"",B==="current"?"_top":void 0,p)};
B==="new"&&(N(),N=null);eW(this.context.logger,I,N,S);wbV(a)||(I=g.oV(),S=p.itct,I&&S&&g.Sy(I,g.Vb(S)))}}mE(){this.Rk.clear();this.BI.clear();super.mE()}createElement(r){r=new g.H(r);g.Z(this,r);return r.element}};var NDV=class extends yyC{constructor(r,p,I){super(p,I);this.V=r;this.eventId=null;this.p7=this.z$=this.xE=this.Z=this.isInitialized=!1;this.cards=[];this.sD=this.C=this.e_=this.J=this.HI=this.W=null;this.iC=[];this.L=this.D=this.GI=this.dM=null;this.K=0;this.UD=new g.pa(()=>{},I.qX.bj?4E3:3E3);
g.Z(this,this.UD);this.Lg=new g.pa(()=>{});
g.Z(this,this.Lg);this.WI=new Oln(I,(S,a,B,N,v,e)=>{L3(this,S,a,B,N,v,e)});
this.Y=new g.H({S:"div",O:"iv-drawer",j:{id:"iv-drawer"},A:[{S:"div",O:"iv-drawer-header",j:{"aria-role":"heading"},A:[{S:"span",O:"iv-drawer-header-text"},{S:"button",vI:["iv-drawer-close-button","ytp-button"],j:{"aria-label":"Hide cards",tabindex:"0"}}]},{S:"div",O:"iv-drawer-content"}]});g.Z(this,this.Y);this.N=this.Y.element;this.Yu=new g.Pc(this.Y,330);g.Z(this,this.Yu);this.T5=g.L2("iv-drawer-header-text",this.N);this.U=g.L2("iv-drawer-content",this.N);this.addCueRange(0,I.videoData.lengthSeconds*
1E3,"",()=>{this.xE&&Is(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.xE=this.Z)&&i9(this)});
this.hG=new g.oM(this);g.Z(this,this.hG);this.V.addEventListener("videodatachange",this.TC.bind(this))}TC(){this.L&&$Z(this,this.L)}isAvailable(){var r;if(r=!!this.cards.length)(r=this.V.getRootNode())?(r=g.RA(r),r=173<r.width&&173<r.height):r=!1;return r}wM(){const r=this.isAvailable();g.rD(this.wu(),r);g.K(this.context.V.getRootNode(),g.yj.IV_DRAWER_ENABLED,r);o_(this.V)}destroy(){this.V.z_(!1);try{this.V.getRootNode().removeChild(this.N)}catch(r){}g.au(this.iC);this.hG.U();this.HI&&this.HI.dispose();
this.J&&this.J.dispose();super.destroy()}Hb(){this.context.W.listen(g.L2("iv-drawer-close-button",this.N),"click",this.RP,this);this.context.W.listen(this.U,"touchend",()=>{this.UD.start()});
this.context.W.listen(this.U,"scroll",this.L7,this);this.context.U.subscribe("onHideControls",()=>{this.z$=!0});
this.context.U.subscribe("onShowControls",()=>{this.z$=!1});
this.context.U.subscribe("onVideoAreaChange",()=>{this.z$=g.BX(this.V.getRootNode(),"ytp-autohide")});
this.iC.push(g.ST("iv-button-shown",this.kE,this));this.iC.push(g.ST("iv-button-hidden",this.Dk,this));ZxY(this)}findLastIndex(r){if(this.cards.length===0)return 0;const p=g.IU(this.cards,I=>r.H0.startMs>I.H0.startMs||r.H0.startMs===I.H0.startMs&&r.H0.timestamp>=I.H0.timestamp?!0:!1);
return p===-1?0:p+1}RP(){if(this.Z){eW(this.context.logger,Bw(this).uf.close);var r=g.oV();r&&this.D&&g.Sy(r,this.D);i9(this)}}L7(){g.K(this.N,"iv-drawer-scrolled",this.U.scrollTop>0)}kE(){const r=g.oV();var p=Bw(this);p=p?p.GI:this.GI;r&&p&&g.$2(r,[p])}Dk(){const r=g.oV();var p=Bw(this);p=p?p.GI:this.GI;r&&p&&g.iz(r,[p])}H6(){const r=Bw(this);eW(this.context.logger,r.uf.eM);const p=g.oV();if(p&&r)if(this.V.X("web_infocards_teaser_show_logging_fix")){const I=[];r.ju&&I.push(r.ju);r.GI&&I.push(r.GI);
I.length>0&&g.$2(p,I)}else g.$2(p,[r.ju,r.GI])}We(){const r=g.oV(),p=Bw(this);r&&p&&g.iz(r,[p.ju])}hL(r){const p=Bw(this),I=g.oV();this.W?r?(r=this.context.logger,eW(r,p.uf.dY),r.V.sendVideoStatsEngageEvent(4,void 0),I&&p.ju&&g.Sy(I,p.ju)):(r=this.context.logger,eW(r,p.uf.dY),r.V.sendVideoStatsEngageEvent(4,void 0),I&&p.GI&&g.Sy(I,p.GI)):(r=this.context.logger,eW(r,p.uf.dY),r.V.sendVideoStatsEngageEvent(4,void 0),I&&this.GI&&g.Sy(I,this.GI))}};var dkg=class extends yyC{constructor(r,p,I){super(r,p);this.annotation=I;this.isActive=!1}rM(){super.rM();jAV(this)}show(){super.show();const r=g.oV();var p=this.annotation.data;r&&p&&(p=p.session_data)&&g.$2(r,[g.Vb(p.itct)])}hide(){super.hide();const r=g.oV();var p=this.annotation.data;r&&p&&(p=p.session_data)&&g.iz(r,[g.Vb(p.itct)])}};var nYU=class extends dkg{constructor(r,p,I){super(r,p,I);this.W=null;this.Z=!1;this.U=null}show(){if(!this.isActive){super.show();if(!this.Z){g.NL(this.wu(),"iv-branding");const r=this.annotation.data;this.W=this.createElement({S:"img",vI:["branding-img","iv-click-target"],j:{"aria-label":"Channel watermark",src:r.image_url,width:r.image_width,height:r.image_height}});g.rD(this.W,!1);const p=this.createElement({S:"button",vI:["branding-img-container","ytp-button"]});p.appendChild(this.W);this.wu().appendChild(p);
const I=this.annotation.A_();I&&L3(this,p,I,this.annotation.id,r.session_data);this.Z=!0}g.rD(this.wu(),!0);this.isActive=!0;if(this.W){try{tBP(this,this.W)}catch{}g.NL(this.context.V.getRootNode(),"ytp-branding-shown");this.context.V.getRootNode().style.setProperty("--branding-image-width",`${this.W.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.rD(this.wu(),!1),this.isActive=!1,g.ee(this.context.V.getRootNode(),"ytp-branding-shown"))}destroy(){this.U&&(this.U.dispose(),this.U=
null);g.ee(this.context.V.getRootNode(),"ytp-branding-shown");super.destroy()}};var asR=class{constructor(r,p,I,S,a,B,N){this.W=r;this.Z=p;this.qX=I;this.videoData=S;this.logger=a;this.V=B;this.U=N}};var APa=class extends dkg{constructor(r,p,I){super(r,p,I);this.D=this.isCollapsed=this.Y=!1;this.J=5E3;this.U=this.Z=this.W=this.N=null;this.K=this.createElement({S:"div",vI:["iv-promo-contents"]});this.C=new g.pa(()=>{this.W.setAttribute("aria-hidden","true");g.rD(this.Z,!1);g.rD(this.U,!0)},700,this);
g.Z(this,this.C)}show(){this.isActive||(super.show(),this.Y||(xma(this),this.Y=!0),g.rD(this.wu(),!0),g.eE(function(){g.ee(this.wu(),"iv-promo-inactive")},100,this),this.wu().removeAttribute("aria-hidden"),this.isActive=!0,vw(this),DmU(this),h1C(this,this.J))}hide(){this.isActive&&(g.NL(this.wu(),"iv-promo-inactive"),this.isActive=!1,this.wu().setAttribute("aria-hidden","true"))}Xu(r,p,I,S,a,B){return this.isCollapsed?!1:super.Xu(r,p,I,S,a,B)}UD(r){this.D=!0;
Nz(this,500,r)}WI(){this.D=!1;z1g(this)}iC(r){r.stopPropagation();this.hide()}L(r){r.stopPropagation();vw(this);this.isCollapsed=!0;g.NL(this.wu(),"iv-promo-collapsed-no-delay");this.C.start()}destroy(){this.C.dispose();super.destroy()}};var VDn=class{constructor(r){this.V=r}};g.xV("annotations_module",class extends g.z${constructor(r){super(r);this.iC=this.L=!1;this.loadNumber=0;this.J={};this.logger=new VDn(this.player);this.C=new g.oM(this);this.K=this.N=null;this.events=new g.oM(this);this.CS=this.D=this.W=null;this.rM=[];g.Z(this,this.C);this.C.B(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.C.B(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.C.B(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.C.B(this.player,"resize",I=>{this.publish("resize",I)});
this.C.B(this.player,"presentingplayerstatechange",I=>{this.publish("presentingplayerstatechange",I)});
this.subscribe("presentingplayerstatechange",this.UD,this);this.subscribe("resize",this.Y,this);this.player.G().dM.subscribe("vast_info_card_add",this.WI,this);g.Z(this,this.events);this.wM=this.createElement({S:"div",O:"video-custom-annotations"});this.U=new g.H({S:"div",vI:["ytp-player-content","ytp-iv-player-content"]});g.Z(this,this.U);g.EX(this.player,this.U.element,4);this.U.hide();this.Z=new g.H({S:"div",vI:["ytp-iv-video-content"]});g.Z(this,this.Z);r=this.createElement({S:"div",O:"video-annotations"});
r.appendChild(this.wM);this.Z.element.appendChild(r);this.yy()?this.load():this.player.X("web_fix_annotations")&&(this.N=()=>{this.loaded||this.Cg()||!this.yy()||(uau(this),this.load())},this.player.addEventListener("videodatachange",this.N));
const p=this.createElement({S:"style"});(g.Pa("HEAD")[0]||document.body).appendChild(p);this.addOnDisposeCallback(()=>{g.s3(p)});
if(r=p.sheet){for(const I of WA1)r.insertRule(I,0);for(const I of Xxg)r.insertRule(I,0)}}kN(r,p){if(!mmu(this.player.G().playerStyle))return null;switch(r){case "loadCustomAnnotationsXml":return(r=g.Gx(p))&&b9(this,r),!0;case "removeCustomAnnotationById":return p&&this.W&&(r6(this.W,p),o_(this.player)),!0}return null}getOptions(){return mmu(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}yy(){const r=this.player.getVideoData(),p=r.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return r.Ur||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.X("web_fix_annotations")?R1R(this)?p?.isWatermarkEnforced===!0?!0:p?.isAnnotationsEnabled??!1:!1:R1R(this)}Y(){if(this.Z){var r=this.player.qT().getVideoContentRect(!0);g.Lx(this.Z.element,r.width,r.height);g.YY(this.Z.element,r.left,r.top)}if(this.W){var p=this.player.rB();r=this.W;p=p.width;g.K(r.N,"iv-drawer-small",p<=426);g.K(r.N,"iv-drawer-big",p>=1280)}}UD(r){ryU(this,r.state);r.state.W(2)&&(this.lf()&&this.Ou()&&this.player.getPresentingPlayerType()!==
2&&this.hN(!1),this.z_(!1))}load(){super.load();ryU(this,this.player.getPlayerStateObject());this.loadNumber++;const r=this.player.getVideoData();ilU(this,r);g.EX(this.player,this.Z.element,4);this.Y();var p=g.$0(r);const I=r.uV();if(this.player.X("web_fix_annotations")){if(p&&(p.featuredChannel&&vMV(this,p.featuredChannel,p.annotationId||"branding",r.videoId||null,r.eventId||null),p=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,p?.isWatermarkEnforced&&!p?.isAnnotationsEnabled))return;
I&&Jw(this,I)}else I&&Jw(this,I),p&&p.featuredChannel&&vMV(this,p.featuredChannel,p.annotationId||"branding",r.videoId||null,r.eventId||null);this.CS=g.L2("ytp-cards-button",this.player.getRootNode());r.Ch()&&$k1(this,r)}onVideoDataChange(){}unload(){this.player.Vx("annotations_module");for(const r of Object.keys(this.J))this.J[r].destroy();this.D=null;this.W&&(this.W.destroy(),this.W=null,o_(this.player));this.L=!1;this.K&&(this.K.abort(),this.K=null);this.iC=!1;this.J={};this.U.hide();super.unload();
this.Z.detach();uau(this)}WI(r){r===this.player.getVideoData().videoId&&(this.loaded?BDY(this):this.load())}lf(){return this.W?.isAvailable()||this.iC}Ou(){return!!this.W&&this.W.Z}hN(r,p=!1,I){this.lf();this.W&&(r?I?Is(this.W,I,p):Is(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",p):i9(this.W))}z_(r,p){this.player.publish(r?"cardsteasershow":"cardsteaserhide",p)}mE(){this.player.G().dM.unsubscribe("vast_info_card_add",this.WI,this);g.ee(this.player.getRootNode(),g.yj.IV_DRAWER_OPEN);var r=this.rM,p=g.Y_;for(let I=
0,S=r.length;I<S;I++)p.q7(r[I]);this.rM.length=0;super.mE()}createElement(r){r=new g.H(r);g.Z(this,r);return r.element}});g.xV("creatorendscreen",sPa);})(_yt_player);
