(function(g){var window=this;'use strict';var vf=function(r){r.publish("autonavvisibility")},hFY=function(r,p){g.sX(r,"onAutonavCoundownStarted",p)},eG=function(r){return r.isBackground()&&r.yP()},x_U=function(r,p){p=p.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
r.L=p?.navigationEndpoint;p=p?.trackingParams;r.playButton&&p&&r.V.setTrackingParams(r.playButton.element,p)},Jt=function(r){const p=CJ(r);
var I=Math,S=I.min;var a=r.K?Date.now()-r.K:0;I=S.call(I,a,p);bm(r,Math.ceil((p-I)/1E3));p-I<=500&&r.W()?r.select(!0):r.W()&&r.Y.start()},sL=function(r){var p=r.V.rB(!0,r.V.isFullscreen());
g.K(r.container.element,"ytp-autonav-endscreen-small-mode",r.JZ(p));g.K(r.container.element,"ytp-autonav-endscreen-is-premium",!!r.suggestion&&!!r.suggestion.Eb);g.K(r.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!r.V.IK());g.K(r.V.getRootNode(),"countdown-running",r.W());g.K(r.container.element,"ytp-player-content",r.V.IK());g.tP(r.overlay.element,{width:`${p.width}px`});if(!r.W()){r.V.IK()?bm(r,Math.round(CJ(r)/1E3)):bm(r);p=!!r.suggestion&&!!r.suggestion.TJ;const I=r.V.IK()||!p;g.K(r.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!I&&p);g.K(r.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",I&&!p);r.J.G5(r.V.IK())}},bm=function(r,p=-1){r=r.N.ZH("ytp-autonav-endscreen-upnext-header");
g.bi(r);if(p>=0){p=String(p);const I="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],S="Up next in $SECONDS".indexOf(I);if(S>=0){r.appendChild(g.eB("Up next in $SECONDS".slice(0,S)));const a=g.vb("span");g.ah(a,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Xa(a,p);r.appendChild(a);r.appendChild(g.eB("Up next in $SECONDS".slice(S+I.length)));return}}g.Xa(r,"Up next")},CJ=function(r){return r.V.isFullscreen()?(r=r.V.getVideoData()?.sQ,r===-1||r===void 0?8E3:r):r.V.yW()>=0?r.V.yW():
g.Wt(r.V.G().experiments,"autoplay_time")||1E4},Wf=function(r,p){p=zFU(r,p);
var I=Math,S=I.min;var a=(0,g.u)()-r.K;I=S.call(I,a,p);p=p===0?1:Math.min(I/p,1);r.wM.setAttribute("stroke-dashoffset",`${-211*(p+1)}`);p>=1&&r.W()&&r.api.getPresentingPlayerType()!==3?r.select(!0):r.W()&&r.N.start()},zFU=function(r,p){return p?p:r.api.isFullscreen()?(r=r.api.getVideoData()?.sQ,r===-1||r===void 0?8E3:r):r.api.yW()>=0?r.api.yW():g.Wt(r.api.G().experiments,"autoplay_time")||1E4},Xe=function(r){const p=r.IK();
p!==r.K&&(r.K=p,vf(r.player),r.K?(r.U!==r.W&&r.U.hide(),r.table.hide()):(r.U!==r.W&&r.U.show(),r.table.show()))},OL=function(r){return g.jI(r.player)&&r.N()&&!r.C},y8=function(r){const p=r.IK();
p!==r.Y&&(r.Y=p,vf(r.player))},dA=function(r){return g.jI(r.player)&&r.N()&&!r.J},V8=function(r){const p=r.IK();
p!==r.rM&&(r.rM=p,vf(r.player))},m_U=function(r){r=r.G();
return r.Dk&&!r.Ch&&!r.disableOrganicUi},uvn=function(r){const p=r.player.getVideoData();
if(!p||r.W===p.r6&&r.U===p.T5)return!1;r.W=p.r6;r.U=p.T5;return!0},lka=function(r){r.player.Vx("endscreen");
var p=r.player.getVideoData();p=new g.Y0(Math.max((p.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const I=new g.Y0(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});r.player.W0([p,I])};
g.XG.prototype.yW=g.$9(9,function(){return this.app.yW()});
g.i3.prototype.yW=g.$9(8,function(){return this.getVideoData().FF});
g.WJ.prototype.Ci=g.$9(7,function(r){this.C8().Ci(r)});
g.Q4.prototype.Ci=g.$9(6,function(r){this.xn!==r&&(this.xn=r,this.qI())});
var YOC=class extends g.H{constructor(r){const p=r.G(),I=p.N;super({S:"a",O:"ytp-autonav-suggestion-card",j:{href:"{{url}}",target:I?p.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},A:[{S:"div",vI:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],j:{style:"{{background}}"},A:[{S:"div",j:{"aria-label":"{{timestamp}}"},vI:["ytp-autonav-timestamp"],uC:"{{duration}}"},
{S:"div",vI:["ytp-autonav-live-stamp"],uC:"Live"},{S:"div",vI:["ytp-autonav-upcoming-stamp"],uC:"Upcoming"},{S:"div",O:"ytp-autonav-list-overlay",A:[{S:"div",O:"ytp-autonav-mix-text",uC:"Mix"},{S:"div",O:"ytp-autonav-mix-icon"}]}]},{S:"div",vI:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],uC:"{{title}}"},{S:"div",vI:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],uC:"{{author}}"},{S:"div",vI:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
uC:"{{views_and_publish_time}}"}]});this.V=r;this.suggestion=null;this.W=I;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.V.zd(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.V8||void 0)&&this.V.logClick(this.element)}onClick(r){g.n9(r,this.V,this.W,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}}};var wA=class extends g.H{constructor(r,p=!1){super({S:"div",O:"ytp-autonav-endscreen-countdown-overlay"});this.wM=p;this.cancelCommand=this.L=void 0;this.K=0;this.container=new g.H({S:"div",O:"ytp-autonav-endscreen-countdown-container"});g.Z(this,this.container);this.container.Ik(this.element);p=r.G();const I=p.N;this.V=r;this.suggestion=null;this.onVideoDataChange("newdata",this.V.getVideoData());this.B(r,"videodatachange",this.onVideoDataChange);this.N=new g.H({S:"div",O:"ytp-autonav-endscreen-upnext-container",
j:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},A:[{S:"div",O:"ytp-autonav-endscreen-upnext-header"},{S:"div",O:"ytp-autonav-endscreen-upnext-alternative-header",uC:"{{autoplayAlternativeHeader}}"},{S:"a",O:"ytp-autonav-endscreen-link-container",j:{href:"{{url}}",target:I?p.Y:""},A:[{S:"div",O:"ytp-autonav-endscreen-upnext-thumbnail",j:{style:"{{background}}"},A:[{S:"div",j:{"aria-label":"{{timestamp}}"},
vI:["ytp-autonav-timestamp"],uC:"{{duration}}"},{S:"div",vI:["ytp-autonav-live-stamp"],uC:"Live"},{S:"div",vI:["ytp-autonav-upcoming-stamp"],uC:"Upcoming"}]},{S:"div",O:"ytp-autonav-endscreen-video-info",A:[{S:"div",O:"ytp-autonav-endscreen-premium-badge"},{S:"div",O:"ytp-autonav-endscreen-upnext-title",uC:"{{title}}"},{S:"div",O:"ytp-autonav-endscreen-upnext-author",uC:"{{author}}"},{S:"div",O:"ytp-autonav-view-and-date",uC:"{{views_and_publish_time}}"},{S:"div",O:"ytp-autonav-author-and-view",uC:"{{author_and_views}}"}]}]}]});
g.Z(this,this.N);this.N.Ik(this.container.element);I||this.B(this.N.ZH("ytp-autonav-endscreen-link-container"),"click",this.WI);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.N.ZH("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.H({S:"div",O:"ytp-autonav-overlay"});g.Z(this,this.overlay);this.overlay.Ik(this.container.element);this.J=new g.H({S:"div",O:"ytp-autonav-endscreen-button-container"});g.Z(this,this.J);this.J.Ik(this.container.element);
this.cancelButton=new g.H({S:"button",vI:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],j:{"aria-label":"Cancel autoplay"},uC:"Cancel"});g.Z(this,this.cancelButton);this.cancelButton.Ik(this.J.element);this.cancelButton.listen("click",this.UD,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.H({S:"a",vI:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],j:{href:"{{url}}",role:"button","aria-label":"Play next video"},uC:"Play Now"});g.Z(this,this.playButton);this.playButton.Ik(this.J.element);this.playButton.listen("click",this.WI,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(p=this.V.getVideoData())&&x_U(this,p);this.Y=new g.pa(()=>{Jt(this)},500);
g.Z(this,this.Y);this.rM();this.B(r,"autonavvisibility",this.rM)}D(r){this.suggestion!==r&&(this.suggestion=r,g.Mv(this.N,r),this.playButton.updateValue("url",this.suggestion.PS()),sL(this))}W(){return this.K>0}C(){this.W()||(this.K=Date.now(),Jt(this),hFY(this.V,CJ(this)),g.K(this.V.getRootNode(),"countdown-running",this.W()))}Z(){this.U();Jt(this);const r=this.N.ZH("ytp-autonav-endscreen-upnext-header");r&&g.Xa(r,"Up next")}U(){this.W()&&(this.Y.stop(),this.K=0)}select(r=!1){this.V.nextVideo(!1,
r);this.U()}WI(r){g.n9(r,this.V)&&(r.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):r.currentTarget===this.N.ZH("ytp-autonav-endscreen-link-container")&&(r=this.N.ZH("ytp-autonav-endscreen-link-container"),this.V.logVisibility(r,!0),this.V.logClick(r)),this.L?(g.sX(this.V,"innertubeCommand",this.L),this.U()):this.select())}UD(){this.V.logClick(this.cancelButton.element);g.k0(this.V,!0);this.cancelCommand&&g.sX(this.V,"innertubeCommand",this.cancelCommand)}onVideoDataChange(r,
p){x_U(this,p);this.cancelCommand=p.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}rM(){const r=this.V.IK();this.wM&&this.ez!==r&&this.G5(r);sL(this);this.V.logVisibility(this.container.element,r);this.V.logVisibility(this.cancelButton.element,r);this.V.logVisibility(this.N.ZH("ytp-autonav-endscreen-link-container"),r);this.V.logVisibility(this.playButton.element,r)}JZ(r){return r.width<400||r.height<459}};var fJ=class extends g.H{constructor(r,p){super({S:"div",vI:["html5-endscreen","ytp-player-content",p||"base-endscreen"]});this.created=!1;this.player=r}create(){this.created=!0}destroy(){this.created=!1}N(){return!1}IK(){return!1}L(){return!1}};var GI=class extends g.H{constructor(r){super({S:"div",vI:["ytp-upnext","ytp-player-content"],j:{"aria-label":"{{aria_label}}"},A:[{S:"div",O:"ytp-cued-thumbnail-overlay-image",j:{style:"{{background}}"}},{S:"span",O:"ytp-upnext-top",A:[{S:"span",O:"ytp-upnext-header",uC:"Up Next"},{S:"span",O:"ytp-upnext-title",uC:"{{title}}"},{S:"span",O:"ytp-upnext-author",uC:"{{author}}"}]},{S:"a",O:"ytp-upnext-autoplay-icon",j:{role:"button",href:"{{url}}","aria-label":"Play next video"},A:[{S:"svg",j:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},A:[{S:"circle",O:"ytp-svg-autoplay-circle",j:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{S:"circle",O:"ytp-svg-autoplay-ring",j:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{S:"path",O:"ytp-svg-fill",j:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{S:"span",O:"ytp-upnext-bottom",A:[{S:"span",O:"ytp-upnext-cancel"},
{S:"span",O:"ytp-upnext-paused",uC:"Autoplay is paused"}]}]});this.api=r;this.cancelButton=null;this.wM=this.ZH("ytp-svg-autoplay-ring");this.Y=this.notification=this.N=this.suggestion=null;this.L=new g.pa(this.J,5E3,this);this.K=0;var p=this.ZH("ytp-upnext-cancel");this.cancelButton=new g.H({S:"button",vI:["ytp-upnext-cancel-button","ytp-button"],j:{tabindex:"0","aria-label":"Cancel autoplay"},uC:"Cancel"});g.Z(this,this.cancelButton);this.cancelButton.listen("click",this.WI,this);this.cancelButton.Ik(p);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.Z(this,this.L);this.api.createClientVe(this.element,this,18788);p=this.ZH("ytp-upnext-autoplay-icon");this.B(p,"click",this.UD);this.api.createClientVe(p,this,115130);this.rM();this.B(r,"autonavvisibility",this.rM);this.B(r,"mdxnowautoplaying",this.dM);this.B(r,"mdxautoplaycanceled",this.e_);g.K(this.element,"ytp-upnext-mobile",this.api.G().U)}J(){this.notification&&(this.L.stop(),this.Pe(this.Y),this.Y=null,this.notification.close(),
this.notification=null)}D(r){this.suggestion=r;g.Mv(this,r,"hqdefault.jpg")}rM(){this.G5(this.api.IK());this.api.logVisibility(this.element,this.api.IK());this.api.logVisibility(this.ZH("ytp-upnext-autoplay-icon"),this.api.IK());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.IK())}z$(){window.focus();this.J()}C(r){this.W()||(g.Bd("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.K=(0,g.u)(),this.N=new g.pa(()=>{Wf(this,r)},25),Wf(this,r),hFY(this.api,zFU(this,
r)));
g.ee(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}W(){return!!this.N}Z(){this.U();this.K=(0,g.u)();Wf(this);g.NL(this.element,"ytp-upnext-autoplay-paused")}U(){this.W()&&(this.N.dispose(),this.N=null)}select(r=!1){if(this.api.G().X("autonav_notifications")&&r&&window.Notification&&typeof document.hasFocus==="function"){const p=Notification.permission;p==="default"?Notification.requestPermission():p!=="granted"||document.hasFocus()||(this.J(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.w3()}),this.Y=this.B(this.notification,"click",this.z$),this.L.start())}this.U();this.api.nextVideo(!1,r)}UD(r){!g.Wb(this.cancelButton.element,r.target)&&g.n9(r,this.api)&&(this.api.IK()&&this.api.logClick(this.ZH("ytp-upnext-autoplay-icon")),this.select())}WI(){this.api.IK()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.k0(this.api,!0)}dM(r){this.api.getPresentingPlayerType();this.show();this.C(r)}e_(){this.api.getPresentingPlayerType();
this.U();this.hide()}mE(){this.U();this.J();super.mE()}};var U_C=class extends fJ{constructor(r){super(r,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.H({S:"div",O:"ytp-suggestion-panel",A:[{S:"div",vI:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],uC:"More videos"}]});this.Y=new g.H({S:"div",O:"ytp-suggestions-container"});this.videos=[];this.Z=null;this.K=this.D=!1;this.U=new wA(this.player);g.Z(this,this.U);this.U.Ik(this.element);r.getVideoData().T5?this.W=this.U:(this.W=new GI(r),g.EX(this.player,
this.W.element,4),g.Z(this,this.W));this.overlay=new g.H({S:"div",O:"ytp-autonav-overlay-cancelled-state"});g.Z(this,this.overlay);this.overlay.Ik(this.element);this.C=new g.oM(this);g.Z(this,this.C);g.Z(this,this.table);this.table.Ik(this.element);this.table.show();g.Z(this,this.Y);this.Y.Ik(this.table.element);this.hide()}create(){super.create();this.C.B(this.player,"appresize",this.J);this.C.B(this.player,"onVideoAreaChange",this.J);this.C.B(this.player,"videodatachange",this.onVideoDataChange);
this.C.B(this.player,"autonavchange",this.rM);this.C.B(this.player,"onAutonavCancelled",this.WI);this.onVideoDataChange()}show(){super.show();(this.D||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&g.k0(this.player,!1);g.jI(this.player)&&this.N()&&!this.Z?(Xe(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||eG(this.player.v9())&&this.player.X("web_player_pip_logging_fix")?this.W.select(!0):this.W.C():this.videoData.autonavState===3&&this.W.Z()):(g.k0(this.player,
!0),Xe(this));this.J()}hide(){super.hide();this.W.Z();Xe(this)}J(){var r=this.player.rB(!0,this.player.isFullscreen());Xe(this);sL(this.U);g.K(this.element,"ytp-autonav-cancelled-small-mode",this.JZ(r));g.K(this.element,"ytp-autonav-cancelled-tiny-mode",this.D$(r));g.K(this.element,"ytp-autonav-cancelled-mini-mode",r.width<=400||r.height<=360);this.overlay&&g.tP(this.overlay.element,{width:`${r.width}px`});if(!this.K)for(r=0;r<this.videos.length;r++)g.K(this.videos[r].element,"ytp-suggestion-card-with-margin",
r%2===1)}onVideoDataChange(){var r=this.player.getVideoData();if(this.videoData!==r&&r){this.videoData=r;r=this.videoData.suggestions;var p=this.videoData.Y();p&&(this.W.D(p),this.W!==this.U&&this.U.D(p));if(r&&r.length)for(let S=0;S<F31.length;++S){var I=F31[S];r&&r[I]&&(this.videos[S]=new YOC(this.player),p=this.videos[S],I=r[I],p.suggestion!==I&&(p.suggestion=I,g.Mv(p,I)),g.Z(this,this.videos[S]),this.videos[S].Ik(this.Y.element))}this.J()}}rM(r){r===1?(this.D=!1,this.Z=this.videoData.clientPlaybackNonce,
this.W.U(),this.ez&&this.J()):(this.D=!0,this.IK()&&(r===2?this.W.C():r===3&&this.W.Z()))}WI(r){r?this.rM(1):(this.Z=null,this.D=!1)}N(){return this.videoData.autonavState!==1}JZ(r){return(r.width<910||r.height<459)&&!this.D$(r)&&!(r.width<=400||r.height<=360)}D$(r){return r.width<800&&!(r.width<=400||r.height<=360)}IK(){return this.ez&&g.jI(this.player)&&this.N()&&!this.Z}},F31=[1,3,2,4];var PVr=class extends fJ{constructor(r){super(r,"videowall-endscreen");this.V=r;this.stills=[];this.C=this.videoData=null;this.J=this.Y=!1;this.rM=null;g.NL(this.element,"modern-videowall-endscreen");this.U=new g.oM(this);g.Z(this,this.U);this.K=new g.pa(()=>{g.NL(this.element,"ytp-show-tiles")},0);
g.Z(this,this.K);this.table=new g.mg({S:"div",O:"ytp-modern-endscreen-content"});g.Z(this,this.table);this.table.Ik(this.element);r.getVideoData().T5?this.W=new wA(r,!0):this.W=new GI(r);g.Z(this,this.W);g.EX(this.player,this.W.element,4);r.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var r=this.player.getVideoData();r&&(this.videoData=r);this.Z();this.U.B(this.player,"appresize",this.Z);this.U.B(this.player,"onVideoAreaChange",this.Z);this.U.B(this.player,"videodatachange",
this.onVideoDataChange);this.U.B(this.player,"autonavchange",this.D);this.U.B(this.player,"onAutonavCancelled",this.WI);r=this.videoData.autonavState;r!==this.rM&&this.D(r);this.U.B(this.element,"transitionend",this.UD)}destroy(){this.U.U();g.nd(this.stills);this.stills=[];super.destroy();g.ee(this.element,"ytp-show-tiles");this.K.stop();this.rM=this.videoData.autonavState}N(){return this.videoData.autonavState!==1}show(){const r=this.ez;super.show();g.ee(this.element,"ytp-show-tiles");this.player.G().U?
g.Ih(this.K):this.K.start();(this.J||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.k0(this.player,!1);OL(this)?(y8(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||eG(this.player.v9())&&this.player.X("web_player_pip_logging_fix")?this.W.select(!0):this.W.C():this.videoData.autonavState===3&&this.W.Z()):(g.k0(this.player,!0),y8(this));r!==this.ez&&this.player.logVisibility(this.element,!0)}hide(){const r=this.ez;super.hide();this.W.Z();y8(this);r!==this.ez&&this.player.logVisibility(this.element,
!1)}UD(r){r.target===this.element&&this.Z()}Z(){const r=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Y()];if(r.length){var p=this.V.rB(!0,this.V.isFullscreen()),I=Math.floor((p.width-64+16)/(g.qe(p.width*.27,250,450)+16));p=Math.min(3,Math.floor((p.height-64)/((p.width-64-(I-1)*16)/I*.5625+70)));g.Ca(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.NL(this.element,`ytp-modern-endscreen-limit-rows-${p}`);
g.K(this.element,"ytp-modern-endscreen-single-item",I===1);g.K(this.element,"ytp-modern-endscreen-row-0",p===0);I=this.table.element;I.ariaLive="polite";this.W.D(this.videoData.Y());this.W instanceof wA&&sL(this.W);g.K(this.element,"ytp-endscreen-takeover",OL(this));y8(this);p=0;I.ariaBusy="true";var S=r.length;for(let a=0;a<S;a++){const B=a%S;let N=this.stills[a];N||(N=new g.CCn(this.player),this.stills[a]=N,I.appendChild(N.element));g.mHr(N,r[B]);p++}this.stills.length=p}}onVideoDataChange(){const r=
this.player.getVideoData({playerType:1});this.videoData!==r&&(r?.Y()?(this.videoData=r,this.Z()):this.player.T$("missg",{vid:r?.videoId||"",cpn:r?.clientPlaybackNonce||""}))}L(){return this.W.W()}D(r){r===1?(this.J=!1,this.C=this.videoData.clientPlaybackNonce,this.W.U(),this.ez&&this.Z()):(this.J=!0,this.ez&&OL(this)&&(r===2?this.W.C():r===3&&this.W.Z()))}WI(r){if(r){for(r=0;r<this.stills.length;r++)this.V.logVisibility(this.stills[r].element,!0);this.D(1)}else this.C=null,this.J=!1;this.Z()}IK(){return this.ez&&
OL(this)}};var nCr=class extends fJ{constructor(r){super(r,"subscribecard-endscreen");this.W=new g.H({S:"div",O:"ytp-subscribe-card",A:[{S:"img",O:"ytp-author-image",j:{src:"{{profilePicture}}"}},{S:"div",O:"ytp-subscribe-card-right",A:[{S:"div",O:"ytp-author-name",uC:"{{author}}"},{S:"div",O:"html5-subscribe-button-container"}]}]});g.Z(this,this.W);this.W.Ik(this.element);const p=r.getVideoData();this.subscribeButton=new g.dl("Subscribe",null,"Unsubscribe",null,!0,!1,p.Jk,p.subscribed,"trailer-endscreen",null,
r,!1);g.Z(this,this.subscribeButton);this.subscribeButton.Ik(this.W.ZH("html5-subscribe-button-container"));this.B(r,"videodatachange",this.OD);this.OD();this.hide()}OD(){const r=this.player.getVideoData();this.W.update({profilePicture:r.profilePicture,author:r.author});this.subscribeButton.channelId=r.Jk;var p=this.subscribeButton;r.subscribed?p.W():p.U()}};var Ajn=class extends g.H{constructor(r){const p=r.G(),I=g.OI||g.Kf?{style:"will-change: opacity"}:void 0,S=p.N,a=["ytp-videowall-still"];p.U&&a.push("ytp-videowall-show-text");super({S:"a",vI:a,j:{href:"{{url}}",target:S?p.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},A:[{S:"div",O:"ytp-videowall-still-image",j:{style:"{{background}}"}},{S:"span",O:"ytp-videowall-still-info",j:{"aria-hidden":"true"},A:[{S:"span",O:"ytp-videowall-still-info-bg",
A:[{S:"span",O:"ytp-videowall-still-info-content",j:I,A:[{S:"span",O:"ytp-videowall-still-info-title",uC:"{{title}}"},{S:"span",O:"ytp-videowall-still-info-author",uC:"{{author_and_views}}"},{S:"span",O:"ytp-videowall-still-info-live",uC:"Live"},{S:"span",O:"ytp-videowall-still-info-duration",uC:"{{duration}}"}]}]}]},{S:"span",vI:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],j:{"aria-hidden":"true"},A:[{S:"span",O:"ytp-videowall-still-listlabel-icon"},"Playlist",{S:"span",
O:"ytp-videowall-still-listlabel-length",A:[" (",{S:"span",uC:"{{playlist_length}}"},")"]}]},{S:"span",vI:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],j:{"aria-hidden":"true"},A:[{S:"span",O:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{S:"span",O:"ytp-videowall-still-listlabel-length",uC:" (50+)"}]}]});this.suggestion=null;this.U=S;this.api=r;this.W=new g.oM(this);g.Z(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.B(r,"videodatachange",
this.onVideoDataChange);r.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.zd(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.V8||void 0)&&this.api.logClick(this.element)}onClick(r){if(g.Wn(this.api.G())&&this.api.X("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let p=this.suggestion.PS();const I={};g.K9(this.api,I);p=g.Cd(p,I);g.AD(p,this.api,r)}else g.n9(r,this.api,
this.U,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}}onVideoDataChange(){const r=this.api.getVideoData(),p=this.api.G();this.U=r.Ur?!1:p.N}};var HKU=class extends fJ{constructor(r){super(r,"videowall-endscreen");this.V=r;this.C=0;this.stills=[];this.J=this.videoData=null;this.K=this.rM=!1;this.WI=null;this.Z=new g.oM(this);g.Z(this,this.Z);this.D=new g.pa(()=>{g.NL(this.element,"ytp-show-tiles")},0);
g.Z(this,this.D);var p=new g.H({S:"button",vI:["ytp-button","ytp-endscreen-previous"],j:{"aria-label":"Previous"},A:[g.X9()]});g.Z(this,p);p.Ik(this.element);p.listen("click",this.dM,this);this.table=new g.mg({S:"div",O:"ytp-endscreen-content"});g.Z(this,this.table);this.table.Ik(this.element);p=new g.H({S:"button",vI:["ytp-button","ytp-endscreen-next"],j:{"aria-label":"Next"},A:[g.O0()]});g.Z(this,p);p.Ik(this.element);p.listen("click",this.wM,this);r.getVideoData().T5?this.W=new wA(r,!0):this.W=
new GI(r);g.Z(this,this.W);g.EX(this.player,this.W.element,4);r.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var r=this.player.getVideoData();r&&(this.videoData=r);this.U();this.Z.B(this.player,"appresize",this.U);this.Z.B(this.player,"onVideoAreaChange",this.U);this.Z.B(this.player,"videodatachange",this.onVideoDataChange);this.Z.B(this.player,"autonavchange",this.Y);this.Z.B(this.player,"onAutonavCancelled",this.UD);r=this.videoData.autonavState;r!==this.WI&&this.Y(r);
this.Z.B(this.element,"transitionend",this.e_)}destroy(){this.Z.U();g.nd(this.stills);this.stills=[];super.destroy();g.ee(this.element,"ytp-show-tiles");this.D.stop();this.WI=this.videoData.autonavState}N(){return this.videoData.autonavState!==1}show(){const r=this.ez;super.show();g.ee(this.element,"ytp-show-tiles");this.player.G().U?g.Ih(this.D):this.D.start();(this.K||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.k0(this.player,!1);dA(this)?(V8(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||eG(this.player.v9())&&this.player.X("web_player_pip_logging_fix")?this.W.select(!0):this.W.C():this.videoData.autonavState===3&&this.W.Z()):(g.k0(this.player,!0),V8(this));r!==this.ez&&this.player.logVisibility(this.element,!0)}hide(){const r=this.ez;super.hide();this.W.Z();V8(this);r!==this.ez&&this.player.logVisibility(this.element,!1)}e_(r){r.target===this.element&&this.U()}U(){var r=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Y()];if(r.length){g.NL(this.element,
"ytp-endscreen-paginate");var p=this.V.rB(!0,this.V.isFullscreen()),I=g.ws(this.V);I&&(I=I.Tw()?48:32,p.width-=I*2);var S=p.width/p.height,a=96/54,B=I=2,N=Math.max(p.width/96,2),v=Math.max(p.height/54,2),e=r.length;var C=e*4;for(C-=4;C>0&&(I<N||B<v);){var b=I/2,J=B/2,W=I<=N-2&&C>=J*4,X=B<=v-2&&C>=b*4;if((b+1)/J*a/S>S/(b/(J+1)*a)&&X)C-=b*4,B+=2;else if(W)C-=J*4,I+=2;else if(X)C-=b*4,B+=2;else break}a=!1;C>=12&&e*4-C<=6&&(B>=4||I>=4)&&(a=!0);C=I*96;N=B*54;S=C/N<S?p.height/N:p.width/C;S=Math.min(S,2);
C=Math.floor(Math.min(p.width,C*S));N=Math.floor(Math.min(p.height,N*S));p=this.table.element;p.ariaLive="polite";g.Lx(p,C,N);g.tP(p,{marginLeft:`${C/-2}px`,marginTop:`${N/-2}px`});this.W.D(this.videoData.Y());this.W instanceof wA&&sL(this.W);g.K(this.element,"ytp-endscreen-takeover",dA(this));V8(this);C+=4;N+=4;S=0;p.ariaBusy="true";for(v=0;v<I;v++)for(b=0;b<B;b++)if(W=S,X=0,a&&v>=I-2&&b>=B-2?X=1:b%2===0&&v%2===0&&(b<2&&v<2?b===0&&v===0&&(X=2):X=2),W=g.Me(W+this.C,e),X!==0){J=this.stills[S];J||(J=
new Ajn(this.player),this.stills[S]=J,p.appendChild(J.element));var d=Math.floor(N*b/B);const M=Math.floor(C*v/I),T=Math.floor(N*(b+X)/B)-d-4,E=Math.floor(C*(v+X)/I)-M-4;g.YY(J.element,M,d);g.Lx(J.element,E,T);g.tP(J.element,"transitionDelay",(b+v)/20+"s");g.K(J.element,"ytp-videowall-still-mini",X===1);g.K(J.element,"ytp-videowall-still-large",X>2);X=Math.max(E,T);g.K(J.element,"ytp-videowall-still-round-large",X>=256);g.K(J.element,"ytp-videowall-still-round-medium",X>96&&X<256);g.K(J.element,"ytp-videowall-still-round-small",
X<=96);W=r[W];J.suggestion!==W&&(J.suggestion=W,X=J.api.G(),d=g.BX(J.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Mv(J,W,d),g.Wn(X)&&!J.api.X("web_player_log_click_before_generating_ve_conversion_params")&&(X=W.PS(),d={},g.OX(J.api,"addEmbedsConversionTrackingParams",[d]),X=g.Cd(X,d),J.updateValue("url",X)),(W=(W=W.sessionData)&&W.itct)&&J.api.setTrackingParams(J.element,W));S++}p.ariaBusy="false";g.K(this.element,"ytp-endscreen-paginate",S<e);for(r=this.stills.length-1;r>=
S;r--)I=this.stills[r],g.s3(I.element),g.Pp(I);this.stills.length=S}}onVideoDataChange(){const r=this.player.getVideoData({playerType:1});this.videoData!==r&&(r?.Y()?(this.C=0,this.videoData=r,this.U()):this.player.T$("missg",{vid:r?.videoId||"",cpn:r?.clientPlaybackNonce||""}))}wM(){this.C+=this.stills.length;this.U()}dM(){this.C-=this.stills.length;this.U()}L(){return this.W.W()}Y(r){r===1?(this.K=!1,this.J=this.videoData.clientPlaybackNonce,this.W.U(),this.ez&&this.U()):(this.K=!0,this.ez&&dA(this)&&
(r===2?this.W.C():r===3&&this.W.Z()))}UD(r){if(r){for(r=0;r<this.stills.length;r++)this.V.logVisibility(this.stills[r].element,!0);this.Y(1)}else this.J=null,this.K=!1;this.U()}IK(){return this.ez&&dA(this)}};var L3C=class extends g.H{constructor(r){super({S:"button",vI:["ytp-watch-on-youtube-button","ytp-button"],uC:"{{content}}"});this.V=r;this.buttonType=this.buttonType=1;this.W();this.buttonType===2&&g.NL(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.W);this.G5(!0)}W(){let r,p;switch(this.buttonType){case 1:r="Watch again on YouTube";p=156915;break;case 2:r="Continue watching on YouTube";p=156942;break;default:r="Continue watching on YouTube",
p=156942}this.update({content:r});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,p)}onClick(r){this.V.X("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.AD(this.getVideoUrl(),this.V,r);this.V.X("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)}getVideoUrl(){var r=!0;switch(this.buttonType){case 1:r=!0;break;case 2:r=!1}r=this.V.getVideoUrl(r,!1,!1,!0);const p=
this.V.G();if(g.Wn(p)){const I={};g.Wn(p)&&g.OX(this.V,"addEmbedsConversionTrackingParams",[I]);r=g.Cd(r,I)}return r}logVisibility(){this.V.logVisibility(this.element,this.ez&&this.iC)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Z9(r){super.Z9(r);this.logVisibility()}};var RFn=class extends fJ{constructor(r){super(r,"watch-again-on-youtube-endscreen");this.watchButton=new L3C(r);g.Z(this,this.watchButton);this.watchButton.Ik(this.element);g.DYU(r)&&(this.W=new g.FQ1(r),g.Z(this,this.W),this.U=new g.H({S:"div",vI:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],j:{tabIndex:"-1"},A:[this.W]}),g.Z(this,this.U),this.W.Ik(this.U.element),this.U.Ik(this.element));r.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.W?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const p=this.U;if(p){var r=this.W.hasSuggestions();g.K(this.element,"ytp-shorts-branded-ui",r);r?p.show():p.hide()}g.ws(this.player)?.Ci(!0);this.player.logVisibility(this.element,!0);this.watchButton.Z9(!0)}}hide(){super.hide();g.ws(this.player)?.Ci(!1);this.player.logVisibility(this.element,!1);this.watchButton.Z9(!1)}};g.xV("endscreen",class extends g.z${constructor(r){super(r);this.endScreen=null;this.W=this.U=this.Z=!1;this.listeners=new g.oM(this);g.Z(this,this.listeners);const p=r.G();r.isEmbedsShortsMode()?this.endScreen=new RFn(r):m_U(r)?(this.Z=!0,uvn(this),this.W?this.endScreen=new U_C(r):p.X("delhi_modern_endscreen")?this.endScreen=new PVr(r):this.endScreen=new HKU(r)):p.Ch?this.endScreen=new nCr(r):this.endScreen=new fJ(r);g.Z(this,this.endScreen);g.EX(r,this.endScreen.element,4);lka(this);this.listeners.B(r,
"videodatachange",this.onVideoDataChange,this);this.listeners.B(r,g.c7("endscreen"),I=>{this.onCueRangeEnter(I)});
this.listeners.B(r,g.g_("endscreen"),I=>{this.onCueRangeExit(I)})}yy(){var r=this.player.getVideoData();
const p=r.mutedAutoplay&&(r.limitedPlaybackDurationInSeconds>0||r.endSeconds>0||r.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!p)return!0;var I=!(!r?.Y()&&!r?.suggestions?.length);I=!m_U(this.player)||I;r=r.JP;const S=this.player.y3();return I&&!r&&!S&&!p}IK(){return this.endScreen.IK()}N5(){return this.IK()?this.endScreen.L():!1}mE(){this.player.Vx("endscreen");super.mE()}load(){{const I=this.player.getVideoData(),S=I.transitionEndpointAtEndOfStream;if(S&&S.videoId){var r=
this.player.NT().Nb.get("heartbeat");var p=I.Y();!p||S.videoId!==p.videoId||I.oQ?(this.player.zd(S.videoId,void 0,void 0,!0,!0,S),r&&r.QY("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),r=!0):r=!1}else r=!1}r||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(r){this.yy()&&(this.endScreen.created||this.endScreen.create(),r.getId()==="load"&&this.load())}onCueRangeExit(r){r.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){lka(this);this.Z&&uvn(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.W?this.endScreen=new U_C(this.player):this.endScreen=new HKU(this.player),g.Z(this,this.endScreen),g.EX(this.player,this.endScreen.element,4))}});})(_yt_player);
